@extends('layouts.librarian')
@section('title', $plan->title.' — '.__('brand.library.name'))
@section('content')
<div class="flex flex-wrap justify-between gap-4"><div><p class="text-xs font-bold uppercase">{{ $plan->year }} · {{ __('news.plan.statuses.'.$plan->status) }}</p><h1 class="font-headline text-4xl text-primary">{{ $plan->title }}</h1></div><a class="admin-btn admin-btn-secondary" href="{{ route('librarian.news.plans.index') }}">{{ __('common.actions.back') }}</a></div>
@php $next = match($plan->status) {'draft'=>'pending_approval','pending_approval'=>'approved','approved'=>'active','active'=>'completed','completed'=>'archived',default=>null}; @endphp
<section class="admin-card mt-6"><h2 class="text-xl font-bold">{{ __('news.plan.workflow') }}</h2><div class="mt-3 flex gap-2">@if($next)<form method="POST" action="{{ route('librarian.news.plans.transition',$plan) }}">@csrf<input type="hidden" name="status" value="{{ $next }}"><button class="admin-btn admin-btn-primary">{{ __('news.plan.actions.'.$next) }}</button></form>@endif</div></section>
<div class="mt-6 grid gap-6 xl:grid-cols-[360px_1fr]">
  <form class="admin-card space-y-3" method="POST" action="{{ route('librarian.news.plans.items.store',$plan) }}">@csrf<h2 class="text-xl font-bold">{{ __('news.plan.add_item') }}</h2><input class="admin-input" type="number" name="item_number" placeholder="№" required><select class="admin-input" name="type">@foreach(\App\Models\News::TYPES as $type)<option value="{{ $type }}">{{ __('news.types.'.$type) }}</option>@endforeach</select><input class="admin-input" name="title_kk" placeholder="{{ __('news.fields.title') }} (KK)" required><input class="admin-input" name="title_ru" placeholder="{{ __('news.fields.title') }} (RU)"><input class="admin-input" name="title_en" placeholder="{{ __('news.fields.title') }} (EN)"><input class="admin-input" type="date" name="planned_date" required><input class="admin-input" name="audience" placeholder="{{ __('news.fields.audience') }}"><textarea class="admin-input" name="expected_result" placeholder="{{ __('news.plan.expected_result') }}"></textarea><button class="admin-btn admin-btn-primary w-full">{{ __('common.actions.save') }}</button></form>
  <div class="space-y-3">@foreach($plan->items as $item)<article class="admin-card"><div class="flex justify-between gap-3"><div><p class="text-xs font-bold">№{{ $item->item_number }} · {{ $item->planned_date->format('d.m.Y') }}</p><h3 class="text-lg font-bold text-primary">{{ $item->title_kk }}</h3><p>{{ __('news.plan.statuses.'.$item->status) }}</p></div>@if($item->publication_id)<a href="{{ route('librarian.news.edit',$item->publication_id) }}">{{ __('news.plan.publication') }}</a>@endif</div>@if($item->status !== 'completed')<form class="mt-3 grid gap-2" method="POST" action="{{ route('librarian.news.plans.items.complete',$item) }}">@csrf<input class="admin-input" type="date" name="actual_date" required><textarea class="admin-input" name="completion_report" minlength="20" required placeholder="{{ __('news.plan.completion_report') }}"></textarea><button class="admin-btn admin-btn-secondary">{{ __('news.plan.complete') }}</button></form>@endif</article>@endforeach</div>
</div>
@endsection
