<?php
return [
    'title' => 'Центр интеграций', 'subtitle' => 'Надёжные коннекторы, очереди, сверка и мониторинг без раскрытия секретов.',
    'start_sync' => 'Запустить синхронизацию',
    'open' => 'Открыть интеграцию', 'overview' => 'Обзор', 'configuration' => 'Конфигурация', 'capabilities' => 'Возможности', 'health' => 'Состояние', 'sync' => 'Синхронизация', 'mapping' => 'Сопоставление', 'conflicts' => 'Конфликты', 'inbox' => 'Входящие', 'outbox' => 'Исходящие / DLQ', 'errors' => 'Ошибки', 'audit' => 'Аудит',
    'last_success' => 'Последний успех', 'last_failure' => 'Последняя ошибка', 'latency' => 'Задержка', 'responsible' => 'Ответственный', 'pending' => 'В очереди', 'dlq' => 'DLQ', 'dry_run' => 'Пробный запуск', 'reconcile' => 'Сверить', 'check' => 'Проверить', 'pause' => 'Приостановить', 'resume' => 'Включить', 'retry' => 'Повторить', 'add_mapping' => 'Добавить mapping', 'resolve' => 'Разрешить', 'secrets_hidden' => 'Секреты управляются вне базы и никогда не показываются.', 'not_connected' => 'Архитектура готова; внешний API или credentials не настроены.',
    'statuses' => ['disabled'=>'Отключено','configured'=>'Настроено','healthy'=>'Работает','degraded'=>'Ограничено','unavailable'=>'Недоступно','credentials_required'=>'Ожидаются credentials','configuration_error'=>'Нужна настройка','contract_expired'=>'Договор истёк','maintenance'=>'Обслуживание','unchecked'=>'Не проверено','pending'=>'Ожидает','processing'=>'Обрабатывается','sent'=>'Отправлено','acknowledged'=>'Подтверждено','failed'=>'Ошибка','dead_letter'=>'Мёртвая очередь','open'=>'Открыт','resolved'=>'Разрешён','completed'=>'Завершено','configuration_required'=>'Нужна конфигурация','provider_not_configured'=>'Провайдер не настроен','secure_connection_failed'=>'Защищённое соединение не установлено','running'=>'Выполняется','awaiting_configuration'=>'Ожидается настройка','not_applicable'=>'Не применяется','not_supported'=>'Не поддерживается'],
    'types' => ['identity'=>'Идентификация','education'=>'Образование','crm'=>'CRM','finance'=>'Финансы','inventory'=>'Учёт/склад','digital_library'=>'Электронные библиотеки','publisher'=>'Издатели','search'=>'Поиск','notification'=>'Уведомления','analytics'=>'Аналитика'],
    'metrics' => ['healthy'=>'Работает','degraded'=>'Ограничено','unavailable'=>'Недоступно','processed'=>'Обработано','failed'=>'Ошибки','dead_letter'=>'DLQ','open_conflicts'=>'Конфликты','average_latency_ms'=>'Средняя задержка, мс'],
];
