<?php

return [
    'title'=>'Качество восстановленных данных','subtitle'=>'Очереди MARC-SQL с учётом семантики источника: ошибки, конфликты, опциональные пустоты и обогащение не смешиваются.','queue_navigation'=>'Очереди сверки','empty'=>'В этой очереди нет открытых задач.',
    'taxonomy'=>['SOURCE_EMPTY'=>'Пусто в источнике','LEGACY_OPTIONAL'=>'Исторически необязательно','MIGRATION_CONFLICT'=>'Конфликт переноса','DATA_ERROR'=>'Ошибка данных','MODERN_ENRICHMENT_NEEDED'=>'Требуется обогащение'],
    'severity'=>['critical'=>'Критично','high'=>'Важно','medium'=>'Средне','low'=>'Низко','info'=>'Справочно'],
    'categories'=>['ksu_unresolved'=>'Неразрешённые связи КСУ','invalid_ksu'=>'Некорректный формат КСУ','orphan_copy'=>'Экземпляры без DOC','duplicate_inventory'=>'Дубли инвентарных номеров','source_current_conflict'=>'Источник против текущего значения','fund_raw'=>'T090w / фонд требует классификации','missing_barcode'=>'Исторические экземпляры без штрихкода','synthetic_inventory'=>'Синтетический инвентарный номер','missing_classification'=>'Нужна классификация','invalid_isbn'=>'Некорректный ISBN','legacy_language'=>'Старый код языка','legacy_encoding'=>'Признаки искажённой кодировки','unmapped_marc'=>'Неизвестные MARC-поля','legacy_without_ksu'=>'Исторические экземпляры без КСУ'],
    'reconciliation'=>['title'=>'Контрольное уравнение КСУ','description'=>'Точно связано + требует сверки + без КСУ в источнике = все исходные INV.','linked'=>'Точно связано','unresolved'=>'Требует сверки','without_ksu'=>'Без КСУ в источнике','total'=>'Итог / source INV','balanced'=>'Сходится','unbalanced'=>'Нарушено'],
    'queues'=>['fund_raw'=>'T090w / фонд','quarantine'=>'Карантин','conflicts'=>'Конфликты','without_ksu'=>'Без КСУ'],
    'fields'=>['context'=>'Исходный контекст','decision'=>'Решение','target_fund'=>'Целевой фонд','decision_note'=>'Обоснование','current_value'=>'Текущее значение','source_value'=>'Значение MARC-SQL','custom_value'=>'Своё значение','kind'=>'Тип','reason'=>'Причина','record_id'=>'ID библиографической записи'],
    'decisions'=>['map_fund'=>'Связать с фондом','note'=>'Классифицировать как примечание','ignore'=>'Оставить как историческое','keep_current'=>'Сохранить текущее','use_legacy'=>'Применить MARC-SQL','custom'=>'Указать своё'],
    'actions'=>['standard_quality'=>'Общее качество','ksu_review'=>'Сверка КСУ','create_record'=>'Создать карточку','link_record'=>'Связать с записью'],
    'hints'=>['create_then_link'=>'После создания свяжите карточку с исходным INV.'],
    'without_ksu_info'=>'Это справочная историческая выборка, а не :count критических ошибок. В числе исходных INV: :orphans карантинных orphan-строк.','messages'=>['fund_reviewed'=>'Решение по T090w сохранено; raw-значение не изменено.','conflict_resolved'=>'Решение конфликта сохранено в аудите.','orphan_linked'=>'Orphan INV связан с библиографической записью.'],'validation'=>['already_resolved'=>'Конфликт уже разрешён.','field_not_supported'=>'Поле нельзя менять этим процессом.','entity_not_supported'=>'Тип объекта не поддерживается.','orphan_not_open'=>'Эта карантинная строка не является открытым orphan INV.','orphan_already_linked'=>'Исходный INV уже связан.','inventory_taken'=>'Инвентарный номер :number уже используется.','barcode_taken'=>'Штрихкод :barcode уже используется.','concurrent_duplicate'=>'Параллельная операция уже заняла этот номер или штрихкод.'],
];
