<?php
return [
    'title' => 'Integration Center', 'subtitle' => 'Reliable connectors, message queues, reconciliation and health without exposing secrets.',
    'start_sync' => 'Start sync',
    'open' => 'Open integration', 'overview' => 'Overview', 'configuration' => 'Configuration', 'capabilities' => 'Capabilities', 'health' => 'Health', 'sync' => 'Sync', 'mapping' => 'Mapping', 'conflicts' => 'Conflicts', 'inbox' => 'Inbox', 'outbox' => 'Outbox / DLQ', 'errors' => 'Errors', 'audit' => 'Audit',
    'last_success' => 'Last success', 'last_failure' => 'Last failure', 'latency' => 'Latency', 'responsible' => 'Responsible', 'pending' => 'Pending', 'dlq' => 'DLQ', 'dry_run' => 'Dry run', 'reconcile' => 'Reconcile', 'check' => 'Health check', 'pause' => 'Pause', 'resume' => 'Resume', 'retry' => 'Retry', 'add_mapping' => 'Add mapping', 'resolve' => 'Resolve', 'secrets_hidden' => 'Secrets are managed outside the database and are never displayed.', 'not_connected' => 'Architecture ready; external API or credentials are not configured.',
    'statuses' => ['disabled'=>'Disabled','configured'=>'Configured','healthy'=>'Healthy','degraded'=>'Degraded','unavailable'=>'Unavailable','credentials_required'=>'Credentials required','configuration_error'=>'Configuration error','contract_expired'=>'Contract expired','maintenance'=>'Maintenance','unchecked'=>'Not checked','pending'=>'Pending','processing'=>'Processing','sent'=>'Sent','acknowledged'=>'Acknowledged','failed'=>'Failed','dead_letter'=>'Dead letter','open'=>'Open','resolved'=>'Resolved','completed'=>'Completed','configuration_required'=>'Configuration required','provider_not_configured'=>'Provider not configured','secure_connection_failed'=>'Secure connection failed','running'=>'Running','awaiting_configuration'=>'Awaiting configuration','not_applicable'=>'Not applicable','not_supported'=>'Not supported'],
    'types' => ['identity'=>'Identity','education'=>'Education','crm'=>'CRM','finance'=>'Finance','inventory'=>'Inventory','digital_library'=>'Digital libraries','publisher'=>'Publishers','search'=>'Search','notification'=>'Notifications','analytics'=>'Analytics'],
    'metrics' => ['healthy'=>'Healthy','degraded'=>'Degraded','unavailable'=>'Unavailable','processed'=>'Processed','failed'=>'Failed','dead_letter'=>'DLQ','open_conflicts'=>'Conflicts','average_latency_ms'=>'Avg latency, ms'],
];
