<?php

return [
    'title'=>'Recovered data quality','subtitle'=>'Source-aware MARC-SQL queues keep errors, conflicts, optional legacy gaps and modern enrichment separate.','queue_navigation'=>'Review queues','empty'=>'This queue has no open work.',
    'taxonomy'=>['SOURCE_EMPTY'=>'Empty in source','LEGACY_OPTIONAL'=>'Legacy optional','MIGRATION_CONFLICT'=>'Migration conflict','DATA_ERROR'=>'Data error','MODERN_ENRICHMENT_NEEDED'=>'Modern enrichment'],
    'severity'=>['critical'=>'Critical','high'=>'High','medium'=>'Medium','low'=>'Low','info'=>'Information'],
    'categories'=>['ksu_unresolved'=>'Unresolved KSU links','invalid_ksu'=>'Malformed KSU values','orphan_copy'=>'Copies without DOC','duplicate_inventory'=>'Duplicate inventory numbers','source_current_conflict'=>'Source/current conflicts','fund_raw'=>'T090w / fund classification','missing_barcode'=>'Historical copies without barcode','synthetic_inventory'=>'System-generated fallback inventory number','missing_classification'=>'Classification enrichment','invalid_isbn'=>'Invalid ISBN','legacy_language'=>'Legacy language code','legacy_encoding'=>'Legacy encoding evidence','unmapped_marc'=>'Unmapped MARC fields','legacy_without_ksu'=>'Historical copies without KSU'],
    'reconciliation'=>['title'=>'KSU control equation','description'=>'Exactly linked + requires review + no KSU in source = every source INV row.','linked'=>'Exactly linked','unresolved'=>'Requires review','without_ksu'=>'No KSU in source','total'=>'Total / source INV','balanced'=>'Balanced','unbalanced'=>'Unbalanced'],
    'queues'=>['fund_raw'=>'T090w / fund','quarantine'=>'Quarantine','conflicts'=>'Conflicts','without_ksu'=>'Without KSU'],
    'fields'=>['context'=>'Source context','decision'=>'Decision','target_fund'=>'Target fund','decision_note'=>'Rationale','current_value'=>'Current value','source_value'=>'MARC-SQL value','custom_value'=>'Custom value','kind'=>'Kind','reason'=>'Reason','record_id'=>'Bibliographic record ID'],
    'decisions'=>['map_fund'=>'Map to fund','note'=>'Classify as note','ignore'=>'Keep as historical','keep_current'=>'Keep current','use_legacy'=>'Apply MARC-SQL','custom'=>'Use custom value'],
    'actions'=>['standard_quality'=>'General quality','ksu_review'=>'KSU review','create_record'=>'Create record','link_record'=>'Link to record'],'hints'=>['create_then_link'=>'After creation, link the record to this source INV row.'],
    'without_ksu_info'=>'This is an informational historical set, not :count critical errors. It includes :orphans quarantined orphan INV rows.','messages'=>['fund_reviewed'=>'The T090w decision was saved; the raw value was not changed.','conflict_resolved'=>'The conflict decision was recorded in the audit log.','orphan_linked'=>'The orphan INV row was linked to a bibliographic record.'],'validation'=>['already_resolved'=>'The conflict has already been resolved.','field_not_supported'=>'This field cannot be changed by this workflow.','entity_not_supported'=>'This entity type is not supported.','orphan_not_open'=>'This quarantine row is not an open orphan INV.','orphan_already_linked'=>'The source INV row is already linked.','inventory_taken'=>'Inventory number :number is already in use.','barcode_taken'=>'Barcode :barcode is already in use.','concurrent_duplicate'=>'A concurrent operation already claimed this number or barcode.'],
];
