<?php
return [
    'title' => 'Интеграциялар орталығы', 'subtitle' => 'Құпияларды ашпайтын сенімді коннекторлар, кезектер, салыстыру және мониторинг.',
    'start_sync' => 'Синхрондауды іске қосу',
    'open' => 'Интеграцияны ашу', 'overview' => 'Шолу', 'configuration' => 'Конфигурация', 'capabilities' => 'Мүмкіндіктер', 'health' => 'Күйі', 'sync' => 'Синхрондау', 'mapping' => 'Сәйкестендіру', 'conflicts' => 'Қайшылықтар', 'inbox' => 'Кіріс', 'outbox' => 'Шығыс / DLQ', 'errors' => 'Қателер', 'audit' => 'Аудит',
    'last_success' => 'Соңғы сәтті әрекет', 'last_failure' => 'Соңғы қате', 'latency' => 'Кідіріс', 'responsible' => 'Жауапты', 'pending' => 'Кезекте', 'dlq' => 'DLQ', 'dry_run' => 'Сынақ іске қосу', 'reconcile' => 'Салыстыру', 'check' => 'Тексеру', 'pause' => 'Тоқтату', 'resume' => 'Қосу', 'retry' => 'Қайталау', 'add_mapping' => 'Mapping қосу', 'resolve' => 'Шешу', 'secrets_hidden' => 'Құпиялар дерекқордан тыс басқарылады және көрсетілмейді.', 'not_connected' => 'Архитектура дайын; сыртқы API немесе credentials бапталмаған.',
    'statuses' => ['disabled'=>'Өшірулі','configured'=>'Бапталған','healthy'=>'Жұмыс істейді','degraded'=>'Шектеулі','unavailable'=>'Қолжетімсіз','credentials_required'=>'Credentials күтілуде','configuration_error'=>'Баптау қажет','contract_expired'=>'Шарт мерзімі аяқталған','maintenance'=>'Қызмет көрсету','unchecked'=>'Тексерілмеген','pending'=>'Күтуде','processing'=>'Өңделуде','sent'=>'Жіберілді','acknowledged'=>'Расталды','failed'=>'Қате','dead_letter'=>'Өлі кезек','open'=>'Ашық','resolved'=>'Шешілді','completed'=>'Аяқталды','configuration_required'=>'Конфигурация қажет','provider_not_configured'=>'Провайдер бапталмаған','secure_connection_failed'=>'Қауіпсіз байланыс орнатылмады','running'=>'Орындалуда','awaiting_configuration'=>'Баптау күтілуде','not_applicable'=>'Қолданылмайды','not_supported'=>'Қолдау көрсетілмейді'],
    'types' => ['identity'=>'Сәйкестендіру','education'=>'Білім беру','crm'=>'CRM','finance'=>'Қаржы','inventory'=>'Есеп/қойма','digital_library'=>'Электрондық кітапханалар','publisher'=>'Баспалар','search'=>'Іздеу','notification'=>'Хабарламалар','analytics'=>'Аналитика'],
    'metrics' => ['healthy'=>'Жұмыс істейді','degraded'=>'Шектеулі','unavailable'=>'Қолжетімсіз','processed'=>'Өңделді','failed'=>'Қателер','dead_letter'=>'DLQ','open_conflicts'=>'Қайшылықтар','average_latency_ms'=>'Орташа кідіріс, мс'],
];
