<?php

return [
    'title'=>'Қалпына келтірілген деректер сапасы','subtitle'=>'MARC-SQL дереккөзіне сай кезектер қателерді, қайшылықтарды, тарихи бос орындарды және толықтыруды бөлек көрсетеді.','queue_navigation'=>'Салыстыру кезектері','empty'=>'Бұл кезекте ашық жұмыс жоқ.',
    'taxonomy'=>['SOURCE_EMPTY'=>'Дереккөзде бос','LEGACY_OPTIONAL'=>'Тарихи міндетті емес','MIGRATION_CONFLICT'=>'Көшіру қайшылығы','DATA_ERROR'=>'Дерек қатесі','MODERN_ENRICHMENT_NEEDED'=>'Қазіргі толықтыру керек'],
    'severity'=>['critical'=>'Сындарлы','high'=>'Жоғары','medium'=>'Орташа','low'=>'Төмен','info'=>'Ақпарат'],
    'categories'=>['ksu_unresolved'=>'Шешілмеген КСУ байланыстары','invalid_ksu'=>'Қате КСУ пішімі','orphan_copy'=>'DOC-сыз даналар','duplicate_inventory'=>'Қайталанған түгендеу нөмірлері','source_current_conflict'=>'Дереккөз/ағымдағы қайшылық','fund_raw'=>'T090w / қор жіктеуі','missing_barcode'=>'Штрихкодсыз тарихи даналар','synthetic_inventory'=>'Синтетикалық түгендеу нөмірі','missing_classification'=>'Жіктеуді толықтыру','invalid_isbn'=>'Қате ISBN','legacy_language'=>'Ескі тіл коды','legacy_encoding'=>'Ескі кодтау белгілері','unmapped_marc'=>'Сәйкестендірілмеген MARC өрістері','legacy_without_ksu'=>'КСУ-сыз тарихи даналар'],
    'reconciliation'=>['title'=>'КСУ бақылау теңдеуі','description'=>'Дәл байланысқан + салыстыру керек + дереккөзде КСУ жоқ = барлық бастапқы INV.','linked'=>'Дәл байланысқан','unresolved'=>'Салыстыру керек','without_ksu'=>'Дереккөзде КСУ жоқ','total'=>'Жиынтық / source INV','balanced'=>'Сәйкес','unbalanced'=>'Сәйкес емес'],
    'queues'=>['fund_raw'=>'T090w / қор','quarantine'=>'Карантин','conflicts'=>'Қайшылықтар','without_ksu'=>'КСУ жоқ'],
    'fields'=>['context'=>'Бастапқы контекст','decision'=>'Шешім','target_fund'=>'Мақсатты қор','decision_note'=>'Негіздеме','current_value'=>'Ағымдағы мән','source_value'=>'MARC-SQL мәні','custom_value'=>'Өз мәні','kind'=>'Түрі','reason'=>'Себебі','record_id'=>'Библиографиялық жазба ID'],
    'decisions'=>['map_fund'=>'Қормен байланыстыру','note'=>'Ескертпе деп жіктеу','ignore'=>'Тарихи күйінде қалдыру','keep_current'=>'Ағымдағыны сақтау','use_legacy'=>'MARC-SQL қолдану','custom'=>'Өз мәнін енгізу'],
    'actions'=>['standard_quality'=>'Жалпы сапа','ksu_review'=>'КСУ салыстыру','create_record'=>'Карточка жасау','link_record'=>'Жазбамен байланыстыру'],'hints'=>['create_then_link'=>'Жасағаннан кейін карточканы осы бастапқы INV жолымен байланыстырыңыз.'],
    'without_ksu_info'=>'Бұл :count сындарлы қате емес, ақпараттық тарихи жиын. Оның ішінде :orphans карантиндік orphan INV жолы бар.','messages'=>['fund_reviewed'=>'T090w шешімі сақталды; raw мәні өзгерген жоқ.','conflict_resolved'=>'Қайшылық шешімі аудитке жазылды.','orphan_linked'=>'Orphan INV библиографиялық жазбамен байланыстырылды.'],'validation'=>['already_resolved'=>'Қайшылық бұрын шешілген.','field_not_supported'=>'Бұл өрісті осы процесс арқылы өзгертуге болмайды.','entity_not_supported'=>'Бұл нысан түрі қолданылмайды.','orphan_not_open'=>'Бұл карантин жолы ашық orphan INV емес.','orphan_already_linked'=>'Бастапқы INV бұрын байланыстырылған.','inventory_taken'=>':number түгендеу нөмірі қолданылып жатыр.','barcode_taken'=>':barcode штрихкоды қолданылып жатыр.','concurrent_duplicate'=>'Қатар операция бұл нөмірді немесе штрихкодты алып қойды.'],
];
