@if (($homepageNews ?? collect())->isNotEmpty())
@php $criticalNews = $homepageNews->first(fn ($item) => $item->importance === 'critical'); @endphp
<section class="mx-auto max-w-7xl py-16" aria-labelledby="homepage-news-title">
  @if($criticalNews)<aside role="alert" class="mb-8 flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-red-200 bg-red-50 p-5 text-red-950"><div><strong class="block">{{ __('news.types.'.$criticalNews->type) }}</strong><span>{{ $criticalNews->localized('title') }}</span></div><a class="font-bold underline" href="{{ $withLang('/news/'.$criticalNews->localizedSlug()) }}">{{ __('common.actions.view') }}</a></aside>@endif
  <div class="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p class="text-xs font-bold uppercase tracking-[.2em] text-teal-700">{{ __('news.homepage.eyebrow') }}</p><h2 id="homepage-news-title" class="font-headline text-4xl text-primary">{{ __('news.homepage.title') }}</h2><p class="mt-2 text-slate-600">{{ __('news.homepage.subtitle') }}</p></div><a class="font-bold text-teal-700" href="{{ $withLang('/news') }}">{{ __('news.homepage.all') }}</a></div>
  <div class="grid gap-5 md:grid-cols-2 xl:grid-cols-3">
    @foreach($homepageNews as $item)<article class="overflow-hidden rounded-2xl border bg-white shadow-sm">@if($item->cover_image)<a href="{{ $withLang('/news/'.$item->localizedSlug()) }}"><img class="aspect-[16/9] w-full object-cover" loading="lazy" src="{{ asset('storage/'.$item->cover_image) }}" alt="{{ $item->localized('image_alt') ?: $item->localized('title') }}"></a>@endif<div class="p-5"><div class="flex justify-between gap-3 text-xs font-bold uppercase text-teal-700"><span>{{ __('news.types.'.$item->type) }}</span><time datetime="{{ $item->published_at?->toIso8601String() }}">{{ $item->published_at?->format('d.m.Y') }}</time></div><h3 class="mt-3 text-xl font-bold text-primary"><a href="{{ $withLang('/news/'.$item->localizedSlug()) }}">{{ $item->localized('title') }}</a></h3><p class="mt-2 text-sm text-slate-600">{{ $item->localized('excerpt') }}</p></div></article>@endforeach
  </div>
</section>
@endif
