@extends('layouts.admin')

@php
    $c = match(app()->getLocale()) {
        'ru' => ['title'=>'Система и резервные копии','sub'=>'Безопасный технический контроль без отображения паролей и ключей доступа','health'=>'Состояние системы','backups'=>'Проверенные резервные копии','create'=>'Создать резервную копию','restore'=>'Проверить восстановление','confirm'=>'Для подтверждения введите RESTORE TO TEST','empty'=>'Резервных копий, созданных из панели, пока нет','verified'=>'Целостность подтверждена','not_verified'=>'Не проверено','available'=>'Работает','unavailable'=>'Недоступно','free'=>'свободно','bytes'=>'байт','health_note'=>'Очередь заданий и планировщик контролируются системным администратором. С этой страницы нельзя случайно остановить или повторно запустить задания.','backup_tech'=>'Защищённый формат PostgreSQL · проверка целостности SHA-256 · восстановление только в изолированную тестовую базу','restore_test'=>'Последняя проверка восстановления','live_note'=>'Восстановление в рабочую базу данных через веб-интерфейс запрещено в целях безопасности.','health_labels'=>['application'=>'Приложение','database'=>'База данных','storage'=>'Хранилище файлов','queue_pending'=>'Заданий в очереди','queue_failed'=>'Заданий с ошибкой','migrations'=>'Изменений структуры БД','filesystem_free'=>'Свободно на диске']],
        'en' => ['title'=>'System & backups','sub'=>'Safe technical control without exposing passwords or access keys','health'=>'System health','backups'=>'Verified backups','create'=>'Create backup','restore'=>'Test restore','confirm'=>'Type RESTORE TO TEST to confirm','empty'=>'No backups have been created from this panel','verified'=>'Integrity verified','not_verified'=>'Not verified','available'=>'Available','unavailable'=>'Unavailable','free'=>'free','bytes'=>'bytes','health_note'=>'The job queue and scheduler are supervised by the system administrator. Jobs cannot be stopped or retried accidentally from this page.','backup_tech'=>'Protected PostgreSQL format · SHA-256 integrity check · restore only to an isolated test database','restore_test'=>'Latest restore test','live_note'=>'Restoring into the production database from the web interface is disabled for safety.','health_labels'=>['application'=>'Application','database'=>'Database','storage'=>'File storage','queue_pending'=>'Queued jobs','queue_failed'=>'Failed jobs','migrations'=>'Database migrations','filesystem_free'=>'Free disk space']],
        default => ['title'=>'Жүйе және сақтық көшірмелер','sub'=>'Құпиясөздер мен кіру кілттерін көрсетпейтін қауіпсіз техникалық бақылау','health'=>'Жүйе күйі','backups'=>'Тексерілген сақтық көшірмелер','create'=>'Сақтық көшірме жасау','restore'=>'Қалпына келтіруді тексеру','confirm'=>'Растау үшін RESTORE TO TEST енгізіңіз','empty'=>'Бұл панельден сақтық көшірме әлі жасалмаған','verified'=>'Тұтастығы расталды','not_verified'=>'Тексерілмеген','available'=>'Жұмыс істейді','unavailable'=>'Қолжетімсіз','free'=>'бос','bytes'=>'байт','health_note'=>'Тапсырмалар кезегі мен жоспарлаушыны жүйе әкімшісі бақылайды. Бұл беттен тапсырмаларды кездейсоқ тоқтату немесе қайталау мүмкін емес.','backup_tech'=>'Қорғалған PostgreSQL форматы · SHA-256 тұтастық тексеруі · тек оқшауланған сынақ дерекқорына қалпына келтіру','restore_test'=>'Соңғы қалпына келтіру сынағы','live_note'=>'Қауіпсіздік үшін веб-интерфейстен жұмыс дерекқорына қалпына келтіруге тыйым салынған.','health_labels'=>['application'=>'Қолданба','database'=>'Дерекқор','storage'=>'Файл қоймасы','queue_pending'=>'Кезектегі тапсырмалар','queue_failed'=>'Қате аяқталған тапсырмалар','migrations'=>'Дерекқор өзгерістері','filesystem_free'=>'Дискідегі бос орын']],
    };
@endphp

@section('title', $c['title'].' — Kazakh University of Technology and Business named after K. Kulazhanov')
@section('content')
<x-admin.page-header :title="$c['title']" :subtitle="$c['sub']" />
@if(session('success'))<div class="mb-6 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-emerald-900">{{ session('success') }}</div>@endif
@if($errors->any())<div class="mb-6 rounded-xl border border-red-200 bg-red-50 p-4 text-red-900">{{ $errors->first() }}</div>@endif

<section class="admin-card mb-8"><h2 class="font-headline text-3xl text-primary">{{ $c['health'] }}</h2><div class="mt-5 grid grid-cols-2 gap-3 lg:grid-cols-4">
@foreach($health as $key => $value)<div class="rounded-xl bg-surface-low p-4"><small class="block text-slate-500">{{ $c['health_labels'][$key] ?? $key }}</small><strong class="mt-1 block break-all">@if(is_bool($value)){{ $value ? $c['available'] : $c['unavailable'] }}@elseif($key === 'filesystem_free'){{ number_format($value / 1024 / 1024 / 1024, 1) }} GB {{ $c['free'] }} @else{{ number_format($value) }}@endif</strong></div>@endforeach
</div><p class="mt-4 text-xs text-slate-500">{{ $c['health_note'] }}</p></section>

<section class="admin-card"><div class="flex flex-wrap items-center justify-between gap-4"><div><h2 class="font-headline text-3xl text-primary">{{ $c['backups'] }}</h2><p class="mt-1 text-sm text-slate-500">{{ $c['backup_tech'] }}</p></div><form method="POST" action="{{ route('admin.system.backups.create') }}">@csrf<button class="admin-btn admin-btn-primary"><span class="material-symbols-outlined">backup</span>{{ $c['create'] }}</button></form></div>
<div class="mt-6 space-y-4">@forelse($backups as $backup)<article class="rounded-xl border border-slate-200 p-5"><div class="flex flex-wrap justify-between gap-4"><div><strong class="font-mono text-sm">{{ $backup['name'] }}</strong><p class="mt-1 text-xs text-slate-500">{{ number_format($backup['size']) }} {{ $c['bytes'] }} · {{ $backup['modified_at'] }}</p><p class="mt-1 break-all font-mono text-[11px] text-slate-500">SHA-256 {{ $backup['sha256'] }}</p></div><x-admin.status-badge :status="$backup['verified'] ? 'verified' : 'failed'" :label="$backup['verified'] ? $c['verified'] : $c['not_verified']" /></div>
@if($backup['restore_test'])<p class="mt-3 rounded-lg bg-emerald-50 p-3 text-xs text-emerald-900">{{ $c['restore_test'] }}: {{ $backup['restore_test']['database'] }} · {{ $backup['restore_test']['verified_at'] }}</p>@endif
<form method="POST" action="{{ route('admin.system.backups.restore-test', $backup['name']) }}" class="mt-4 flex flex-wrap gap-3">@csrf<label class="sr-only" for="confirmation-{{ $loop->index }}">{{ $c['confirm'] }}</label><input id="confirmation-{{ $loop->index }}" name="confirmation" class="admin-input max-w-xs" required placeholder="RESTORE TO TEST" autocomplete="off"><button class="admin-btn admin-btn-secondary"><span class="material-symbols-outlined">restore</span>{{ $c['restore'] }}</button></form></article>@empty<p class="py-8 text-center text-slate-500">{{ $c['empty'] }}</p>@endforelse</div>
<p class="mt-5 rounded-xl bg-amber-50 p-4 text-sm text-amber-900">{{ $c['live_note'] }}</p></section>
@endsection
