<?php

// Scholarly repository seed catalog (PROJECT_CONTEXT §20 — Scientific Works module).
// Guest-visible metadata only; full-text reading stays behind AD authentication
// and the controlled viewer. Structure is deliberately DB-replaceable: a future
// backend phase swaps this config for the app.scientific_works table without
// touching the views.
return [
    'works' => [
        [
            'slug' => 'adaptive-catalog-search-bachelor-2025',
            'type' => 'bachelor_thesis',
            'status' => 'published',
            'year' => 2025,
            'work_language' => 'ru',
            'udc' => '004.85',
            'pages' => 82,
            'faculty_slug' => 'engineering',
            'published_at' => '2025-06-18',
            'i18n' => [
                'ru' => [
                    'title' => 'Адаптивные алгоритмы полнотекстового поиска в библиотечных каталогах',
                    'authors' => ['Айдана Сериккызы'],
                    'faculty' => 'Факультет инжиниринга и информационных технологий',
                    'department' => 'Кафедра «Информационные технологии»',
                    'abstract' => 'Дипломная работа посвящена ранжированию результатов полнотекстового поиска в академических каталогах с учётом доступности экземпляров. Предложен гибридный алгоритм, сочетающий лексические сигналы PostgreSQL FTS с весами предметных рубрик УДК, и выполнена его оценка на обезличенном журнале запросов университетской библиотеки.',
                    'keywords' => ['полнотекстовый поиск', 'ранжирование', 'УДК', 'библиотечные каталоги'],
                ],
                'kk' => [
                    'title' => 'Кітапхана каталогтарындағы толық мәтінді іздеудің бейімделгіш алгоритмдері',
                    'authors' => ['Айдана Серікқызы'],
                    'faculty' => 'Инжиниринг және ақпараттық технологиялар факультеті',
                    'department' => '«Ақпараттық технологиялар» кафедрасы',
                    'abstract' => 'Дипломдық жұмыс академиялық каталогтардағы толық мәтінді іздеу нәтижелерін даналардың қолжетімділігін ескере отырып саралауға арналған. PostgreSQL FTS лексикалық сигналдарын ӘОЖ тақырыптық айдарларының салмақтарымен біріктіретін гибридті алгоритм ұсынылып, университет кітапханасының иесіздендірілген сұраныс журналында бағаланды.',
                    'keywords' => ['толық мәтінді іздеу', 'саралау', 'ӘОЖ', 'кітапхана каталогтары'],
                ],
                'en' => [
                    'title' => 'Adaptive Full-Text Search Ranking for Library Catalogs',
                    'authors' => ['Aidana Serikkyzy'],
                    'faculty' => 'Faculty of Engineering and Information Technology',
                    'department' => 'Department of Information Technology',
                    'abstract' => 'This bachelor thesis studies availability-aware ranking of full-text search results in academic catalogs. It proposes a hybrid algorithm combining PostgreSQL FTS lexical signals with UDC subject-rubric weights and evaluates it on an anonymised query log of the university library.',
                    'keywords' => ['full-text search', 'ranking', 'UDC', 'library catalogs'],
                ],
            ],
        ],
        [
            'slug' => 'tourism-cluster-astana-master-2025',
            'type' => 'master_dissertation',
            'status' => 'published',
            'year' => 2025,
            'work_language' => 'kk',
            'udc' => '338.48',
            'pages' => 116,
            'faculty_slug' => 'economics',
            'published_at' => '2025-11-02',
            'i18n' => [
                'ru' => [
                    'title' => 'Кластерная модель развития делового туризма в агломерации Астаны',
                    'authors' => ['Динара Абылайкызы'],
                    'faculty' => 'Факультет экономики и бизнеса',
                    'department' => 'Кафедра «Туризм и сервис»',
                    'abstract' => 'Магистерская диссертация исследует условия формирования кластера делового туризма в столичной агломерации. На основе интервью с операторами MICE-сегмента и статистики событийной загрузки предложена модель координации инфраструктуры, образовательных программ и событийного календаря города.',
                    'keywords' => ['деловой туризм', 'кластер', 'MICE', 'Астана'],
                ],
                'kk' => [
                    'title' => 'Астана агломерациясындағы іскерлік туризмді дамытудың кластерлік моделі',
                    'authors' => ['Динара Абылайқызы'],
                    'faculty' => 'Экономика және бизнес факультеті',
                    'department' => '«Туризм және сервис» кафедрасы',
                    'abstract' => 'Магистрлік диссертация елорда агломерациясында іскерлік туризм кластерін қалыптастыру шарттарын зерттейді. MICE-сегмент операторларымен жүргізілген сұхбаттар мен іс-шаралық жүктеме статистикасы негізінде инфрақұрылымды, білім бағдарламаларын және қаланың іс-шаралар күнтізбесін үйлестіру моделі ұсынылған.',
                    'keywords' => ['іскерлік туризм', 'кластер', 'MICE', 'Астана'],
                ],
                'en' => [
                    'title' => 'A Cluster Model for Business Tourism Development in the Astana Agglomeration',
                    'authors' => ['Dinara Abylaikyzy'],
                    'faculty' => 'Faculty of Economics and Business',
                    'department' => 'Department of Tourism and Service',
                    'abstract' => 'This master dissertation examines the conditions for forming a business-tourism cluster in the capital agglomeration. Drawing on interviews with MICE operators and event-load statistics, it proposes a model coordinating infrastructure, degree programmes, and the city event calendar.',
                    'keywords' => ['business tourism', 'cluster', 'MICE', 'Astana'],
                ],
            ],
        ],
        [
            'slug' => 'functional-fermented-products-phd-2024',
            'type' => 'phd_dissertation',
            'status' => 'published',
            'year' => 2024,
            'work_language' => 'ru',
            'udc' => '664.3',
            'pages' => 168,
            'faculty_slug' => 'technology',
            'published_at' => '2024-12-10',
            'i18n' => [
                'ru' => [
                    'title' => 'Разработка технологии функциональных кисломолочных продуктов с растительными ингредиентами Казахстана',
                    'authors' => ['Ерлан Байжанович Тлеубаев'],
                    'faculty' => 'Технологический факультет',
                    'department' => 'Кафедра «Технология и стандартизация»',
                    'abstract' => 'Докторская диссертация посвящена обоснованию рецептур и режимов ферментации кисломолочных продуктов, обогащённых местным растительным сырьём. Определены технологические параметры, обеспечивающие стабильность пробиотической микрофлоры, и разработан проект стандарта организации для промышленного выпуска.',
                    'keywords' => ['ферментация', 'функциональные продукты', 'стандартизация', 'пищевые технологии'],
                ],
                'kk' => [
                    'title' => 'Қазақстанның өсімдік ингредиенттері қосылған функционалды ашыған сүт өнімдерінің технологиясын әзірлеу',
                    'authors' => ['Ерлан Байжанұлы Тілеубаев'],
                    'faculty' => 'Технологиялық факультет',
                    'department' => '«Технология және стандарттау» кафедрасы',
                    'abstract' => 'Докторлық диссертация жергілікті өсімдік шикізатымен байытылған ашыған сүт өнімдерінің рецептуралары мен ашыту режимдерін негіздеуге арналған. Пробиотикалық микрофлораның тұрақтылығын қамтамасыз ететін технологиялық параметрлер анықталып, өнеркәсіптік шығарылымға арналған ұйым стандартының жобасы әзірленді.',
                    'keywords' => ['ашыту', 'функционалды өнімдер', 'стандарттау', 'тағам технологиялары'],
                ],
                'en' => [
                    'title' => 'Technology Development for Functional Fermented Dairy Products with Kazakhstani Plant Ingredients',
                    'authors' => ['Yerlan Tleubayev'],
                    'faculty' => 'Faculty of Technology',
                    'department' => 'Department of Technology and Standardisation',
                    'abstract' => 'This doctoral dissertation substantiates formulations and fermentation regimes for dairy products enriched with local plant raw materials. It identifies process parameters that keep the probiotic microflora stable and drafts an organisational standard for industrial production.',
                    'keywords' => ['fermentation', 'functional foods', 'standardisation', 'food technology'],
                ],
            ],
        ],
        [
            'slug' => 'textile-recycling-article-2026',
            'type' => 'article',
            'status' => 'published',
            'year' => 2026,
            'work_language' => 'en',
            'udc' => '677.02',
            'pages' => 14,
            'faculty_slug' => 'technology',
            'published_at' => '2026-02-14',
            'i18n' => [
                'ru' => [
                    'title' => 'Оценка жизненного цикла переработки текстильных отходов лёгкой промышленности',
                    'authors' => ['Гульмира Оспанова', 'Алия Нурланкызы'],
                    'faculty' => 'Технологический факультет',
                    'department' => 'Кафедра «Технология лёгкой промышленности и дизайна»',
                    'abstract' => 'В статье выполнена оценка жизненного цикла трёх сценариев переработки текстильных отходов швейного производства. Показано, что локальная механическая переработка снижает совокупный углеродный след на 27% по сравнению с вывозом на полигон, и сформулированы рекомендации для малых предприятий отрасли.',
                    'keywords' => ['текстильные отходы', 'оценка жизненного цикла', 'лёгкая промышленность', 'устойчивое развитие'],
                ],
                'kk' => [
                    'title' => 'Жеңіл өнеркәсіптің тоқыма қалдықтарын қайта өңдеудің өмірлік циклін бағалау',
                    'authors' => ['Гүлмира Оспанова', 'Әлия Нұрланқызы'],
                    'faculty' => 'Технологиялық факультет',
                    'department' => '«Жеңіл өнеркәсіп технологиясы және дизайн» кафедрасы',
                    'abstract' => 'Мақалада тігін өндірісінің тоқыма қалдықтарын қайта өңдеудің үш сценарийінің өмірлік циклі бағаланған. Жергілікті механикалық қайта өңдеу полигонға шығарумен салыстырғанда жиынтық көміртек ізін 27%-ға азайтатыны көрсетіліп, сала шағын кәсіпорындарына ұсынымдар тұжырымдалған.',
                    'keywords' => ['тоқыма қалдықтары', 'өмірлік циклді бағалау', 'жеңіл өнеркәсіп', 'тұрақты даму'],
                ],
                'en' => [
                    'title' => 'Life-Cycle Assessment of Textile Waste Recycling in Light Industry',
                    'authors' => ['Gulmira Ospanova', 'Aliya Nurlankyzy'],
                    'faculty' => 'Faculty of Technology',
                    'department' => 'Department of Light Industry Technology and Design',
                    'abstract' => 'The article presents a life-cycle assessment of three recycling scenarios for garment-production textile waste. Local mechanical recycling is shown to cut the aggregate carbon footprint by 27% versus landfill disposal, and recommendations are formulated for small enterprises in the sector.',
                    'keywords' => ['textile waste', 'life-cycle assessment', 'light industry', 'sustainability'],
                ],
            ],
        ],
        [
            'slug' => 'ishim-basin-microplastics-report-2025',
            'type' => 'report',
            'status' => 'published',
            'year' => 2025,
            'work_language' => 'ru',
            'udc' => '504.4',
            'pages' => 54,
            'faculty_slug' => 'engineering',
            'published_at' => '2025-09-30',
            'i18n' => [
                'ru' => [
                    'title' => 'Мониторинг микропластика в бассейне реки Есиль: итоговый отчёт полевого сезона 2025 года',
                    'authors' => ['Научная группа кафедры химии и экологии'],
                    'faculty' => 'Факультет инжиниринга и информационных технологий',
                    'department' => 'Кафедра «Химия, химическая технология и экология»',
                    'abstract' => 'Отчёт обобщает результаты полевого сезона по отбору и анализу проб воды и донных отложений на восьми створах бассейна Есиля. Приведены концентрации частиц микропластика по фракциям, картирование источников и методические рекомендации для регионального экологического мониторинга.',
                    'keywords' => ['микропластик', 'экологический мониторинг', 'река Есиль', 'качество воды'],
                ],
                'kk' => [
                    'title' => 'Есіл өзені алабындағы микропластик мониторингі: 2025 жылғы далалық маусымның қорытынды есебі',
                    'authors' => ['Химия және экология кафедрасының ғылыми тобы'],
                    'faculty' => 'Инжиниринг және ақпараттық технологиялар факультеті',
                    'department' => '«Химия, химиялық технология және экология» кафедрасы',
                    'abstract' => 'Есеп Есіл алабының сегіз тұстамасында су мен түптік шөгінділер сынамаларын іріктеу және талдау бойынша далалық маусым нәтижелерін қорытады. Микропластик бөлшектерінің фракциялар бойынша шоғырлануы, көздерді карталау және өңірлік экологиялық мониторингке арналған әдістемелік ұсынымдар келтірілген.',
                    'keywords' => ['микропластик', 'экологиялық мониторинг', 'Есіл өзені', 'су сапасы'],
                ],
                'en' => [
                    'title' => 'Microplastics Monitoring in the Yesil River Basin: Final Report of the 2025 Field Season',
                    'authors' => ['Research Group, Department of Chemistry and Ecology'],
                    'faculty' => 'Faculty of Engineering and Information Technology',
                    'department' => 'Department of Chemistry, Chemical Technology and Ecology',
                    'abstract' => 'The report consolidates field-season results of water and sediment sampling at eight gauging sites of the Yesil basin. It presents microplastic particle concentrations by fraction, source mapping, and methodological recommendations for regional environmental monitoring.',
                    'keywords' => ['microplastics', 'environmental monitoring', 'Yesil River', 'water quality'],
                ],
            ],
        ],
        [
            'slug' => 'sme-esg-reporting-journal-2026',
            'type' => 'journal',
            'status' => 'published',
            'year' => 2026,
            'work_language' => 'ru',
            'udc' => '657.1',
            'pages' => 11,
            'faculty_slug' => 'economics',
            'published_at' => '2026-03-20',
            'i18n' => [
                'ru' => [
                    'title' => 'ESG-отчётность малого и среднего бизнеса Казахстана: барьеры внедрения и учётные практики',
                    'authors' => ['Салтанат Жумагалиева', 'Бауыржан Касымов'],
                    'faculty' => 'Факультет экономики и бизнеса',
                    'department' => 'Кафедра «Финансы и учёт»',
                    'abstract' => 'Публикация университетского журнала анализирует готовность казахстанского МСБ к нефинансовой отчётности. По результатам опроса 142 предприятий выделены ключевые барьеры — кадровый дефицит и отсутствие отраслевых методик — и предложена поэтапная модель внедрения ESG-учёта.',
                    'keywords' => ['ESG', 'нефинансовая отчётность', 'МСБ', 'учёт'],
                ],
                'kk' => [
                    'title' => 'Қазақстанның шағын және орта бизнесіндегі ESG-есептілік: енгізу кедергілері мен есеп тәжірибелері',
                    'authors' => ['Салтанат Жұмағалиева', 'Бауыржан Қасымов'],
                    'faculty' => 'Экономика және бизнес факультеті',
                    'department' => '«Қаржы және есеп» кафедрасы',
                    'abstract' => 'Университет журналының жарияланымы қазақстандық ШОБ-тың қаржылық емес есептілікке дайындығын талдайды. 142 кәсіпорынды сұрау нәтижесінде негізгі кедергілер — кадр тапшылығы мен салалық әдістемелердің болмауы — айқындалып, ESG-есепті кезең-кезеңмен енгізу моделі ұсынылған.',
                    'keywords' => ['ESG', 'қаржылық емес есептілік', 'ШОБ', 'есеп'],
                ],
                'en' => [
                    'title' => 'ESG Reporting in Kazakhstani SMEs: Adoption Barriers and Accounting Practices',
                    'authors' => ['Saltanat Zhumagaliyeva', 'Bauyrzhan Kassymov'],
                    'faculty' => 'Faculty of Economics and Business',
                    'department' => 'Department of Finance and Accounting',
                    'abstract' => 'This university journal publication analyses the readiness of Kazakhstani SMEs for non-financial reporting. A survey of 142 enterprises identifies the key barriers — staffing gaps and missing sector methodologies — and proposes a staged model for adopting ESG accounting.',
                    'keywords' => ['ESG', 'non-financial reporting', 'SME', 'accounting'],
                ],
            ],
        ],
    ],
];
