@extends('layouts.librarian')

@section('title', $inventory->session_number)

@section('content')
<div class="space-y-6">
    <header class="flex flex-wrap items-end justify-between gap-4"><div><p class="admin-kicker">{{ __('librarian.inventory.kicker') }}</p><h1 class="font-headline text-4xl text-primary">{{ $inventory->session_number }}</h1><p class="mt-2 text-slate-600">{{ $inventory->branch?->name }} · {{ $inventory->fund?->name ?? __('librarian.inventory.all_funds') }} · {{ $inventory->shelf_range ?: '—' }}</p></div><a class="admin-btn" href="{{ route('librarian.inventory.export',$inventory) }}">CSV</a></header>
    @if($errors->any())<div class="rounded-xl bg-red-50 p-4 text-red-800">{{ $errors->first() }}</div>@endif
    <section class="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">@foreach(['expected_count'=>'expected','checked'=>'checked','found_count'=>'found','missing_count'=>'missing','requires_review'=>'requires_review'] as $field=>$label)<div class="admin-card"><strong class="font-headline text-3xl text-primary">{{ array_key_exists($field,$analytics) ? $analytics[$field] : $inventory->$field }}</strong><span class="mt-1 block text-sm text-slate-500">{{ __('librarian.inventory.'.$label) }}</span></div>@endforeach</section>
    @if($inventory->status==='draft')<form method="POST" action="{{ route('librarian.inventory.start',$inventory) }}">@csrf<button class="admin-btn admin-btn-primary" type="submit">{{ __('librarian.inventory.start') }}</button></form>@endif
    @if($inventory->status==='running')
    <section class="admin-card"><h2 class="font-headline text-2xl text-primary">{{ __('librarian.inventory.physical_verification') }}</h2><form id="inventory-scan" method="POST" action="{{ route('librarian.inventory.verify',$inventory) }}" class="mt-4 grid gap-3 lg:grid-cols-[1fr_220px_1fr_auto]">@csrf<input id="scan-code" class="admin-input font-mono" name="inventory_number" autocomplete="off" autofocus placeholder="{{ __('librarian.inventory.inventory_number') }}" required><select class="admin-input" name="inventory_condition" required>@foreach(['visible','db_only','unreadable','mismatch'] as $condition)<option value="{{ $condition }}">{{ __('librarian.inventory.inventory_conditions.'.$condition) }}</option>@endforeach</select><input class="admin-input font-mono" name="observed_inventory_number" autocomplete="off" placeholder="{{ __('librarian.inventory.observed_inventory') }}"><button class="admin-btn admin-btn-primary" type="submit">{{ __('librarian.inventory.confirm_found') }}</button></form><p class="mt-2 text-xs text-slate-500">{{ __('librarian.inventory.identity_help') }}</p></section>
    <form method="POST" action="{{ route('librarian.inventory.complete',$inventory) }}" onsubmit="return confirm('{{ __('librarian.inventory.complete_confirm') }}')">@csrf<button class="admin-btn" type="submit">{{ __('librarian.inventory.complete') }}</button></form>
    @endif
    @if($inventory->status==='review')<form method="POST" action="{{ route('librarian.inventory.approve',$inventory) }}" onsubmit="return confirm('{{ __('librarian.inventory.approve_confirm') }}')">@csrf<button class="admin-btn admin-btn-primary" type="submit">{{ __('librarian.inventory.approve') }}</button></form>@endif
    <section class="admin-card"><h2 class="font-headline text-2xl text-primary">{{ __('librarian.inventory.pilot_analytics') }}</h2><dl class="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">@foreach(['location_confirmed','location_corrected','barcodes_assigned','labels_printed','scan_confirmed','median_handling_seconds'] as $metric)<div><dt class="text-xs text-slate-500">{{ __('librarian.inventory.'.$metric) }}</dt><dd class="text-xl font-bold text-primary">{{ $analytics[$metric] ?? '—' }}</dd></div>@endforeach</dl></section>
    <section class="admin-card overflow-x-auto"><h2 class="font-headline text-2xl text-primary">{{ __('librarian.inventory.snapshot') }}</h2><table class="admin-table mt-4"><thead><tr><th>{{ __('librarian.inventory.code') }}</th><th>{{ __('librarian.inventory.book') }}</th><th>{{ __('librarian.inventory.database_location') }}</th><th>{{ __('librarian.inventory.inventory_condition') }}</th><th>{{ __('librarian.inventory.result') }}</th><th>{{ __('librarian.inventory.actions') }}</th></tr></thead><tbody>@foreach($inventory->items as $item)<tr><td class="font-mono">{{ $item->copy?->inventory_number }}</td><td>{{ $item->copy?->bibliographicRecord?->title }}</td><td>{{ $item->copy?->branch?->name ?? '—' }} · {{ $item->copy?->fund?->name ?? '—' }} · {{ $item->copy?->room ?: '—' }} · {{ $item->copy?->shelf_location ?: '—' }}</td><td>{{ __('librarian.inventory.inventory_conditions.'.$item->inventory_condition) }}</td><td>{{ __('librarian.inventory.results.'.$item->result) }}</td><td><div class="flex flex-wrap gap-2">@if($item->verified_at)<form method="POST" action="{{ route('librarian.inventory.location.confirm',[$inventory,$item->copy]) }}">@csrf<label class="text-xs"><input type="checkbox" name="apply_correction" value="1"> {{ __('librarian.inventory.apply_location_correction') }}</label><button class="admin-btn admin-btn-secondary" type="submit">{{ __('librarian.inventory.confirm_location') }}</button></form>@if(blank($item->copy?->barcode))<a class="admin-btn admin-btn-primary" href="{{ route('librarian.copies.show',$item->copy) }}">{{ __('librarian.copies.marking.assign') }}</a>@elseif($item->copy)<a class="admin-btn admin-btn-secondary" href="{{ route('librarian.copies.show',$item->copy) }}">{{ __('librarian.inventory.marking') }}</a>@endif@endif</div></td></tr>@endforeach</tbody></table></section>
</div>
<script>document.getElementById('inventory-scan')?.addEventListener('submit',function(){this.querySelector('button').disabled=true});</script>
@endsection
