@extends('layouts.member')
@section('content')
<a class="text-secondary" href="{{ route('member.incidents.index') }}">← {{ __('common.actions.back') }}</a>
<h1 class="mt-4 font-headline text-4xl">{{ $incident->case_number }}</h1><p class="mt-2">{{ __('incidents.statuses.'.$incident->status) }}</p>
<div class="mt-8 grid gap-6 lg:grid-cols-2">
<section class="rounded-xl bg-white p-6"><h2 class="font-headline text-2xl">{{ __('incidents.sections.incident') }}</h2><dl class="mt-4 space-y-3"><div><dt class="text-xs uppercase text-outline">{{ __('incidents.fields.original_book') }}</dt><dd>{{ $incident->originalCopy?->bibliographicRecord?->title }}</dd></div><div><dt class="text-xs uppercase text-outline">{{ __('incidents.fields.type') }}</dt><dd>{{ __('incidents.types.'.$incident->incident_type) }}</dd></div><div><dt class="text-xs uppercase text-outline">{{ __('incidents.fields.due_at') }}</dt><dd>{{ $incident->resolution_due_at?->format('d.m.Y') ?? '—' }}</dd></div><div><dt class="text-xs uppercase text-outline">{{ __('incidents.fields.decision') }}</dt><dd>{{ $incident->decision_reason ?: '—' }}</dd></div></dl></section>
<section class="rounded-xl bg-white p-6"><h2 class="font-headline text-2xl">{{ __('incidents.sections.fines') }}</h2><p class="mt-4">{{ $incident->fine ? number_format((float)$incident->fine->amount,2,',',' ').' ₸ · '.__('librarian.fines.statuses.'.$incident->fine->status) : __('incidents.no_fine') }}</p></section>
<section class="rounded-xl bg-white p-6 lg:col-span-2"><h2 class="font-headline text-2xl">{{ __('incidents.sections.candidates') }}</h2><div class="mt-4 space-y-3">@forelse($incident->candidates as $candidate)<div class="rounded-lg border p-4"><strong>{{ $candidate->title }}</strong> · {{ $candidate->author }}<p class="text-sm text-on-surface-variant">{{ __('incidents.candidate_statuses.'.$candidate->status) }} @if($candidate->match_score!==null) · {{ $candidate->match_score }}% @endif</p>@if($candidate->reviewed_at)<div class="mt-3 grid gap-2 sm:grid-cols-2">@foreach(\App\Models\Catalog\ReplacementCandidate::REQUIRED_CRITERIA as $criterion)<div class="flex justify-between gap-3 text-xs"><span>{{ __('incidents.criteria.'.$criterion) }}</span><strong class="{{ $candidate->{$criterion} ? 'text-emerald-700' : 'text-red-700' }}">{{ $candidate->{$criterion} ? __('common.yes') : __('common.no') }}</strong></div>@endforeach</div>@endif<p class="mt-2 text-sm">{{ $candidate->reviewer_comment }}</p></div>@empty<p>{{ __('incidents.member.no_candidates') }}</p>@endforelse</div></section>
</div>
@endsection
