@extends('layouts.librarian')
@section('title', __('librarian.copies.marking.batch_title').' — '.__('common.app_name'))
@section('content')
<x-admin.flash />
<x-admin.page-header :eyebrow="__('librarian.copies.eyebrow')" :title="__('librarian.copies.marking.batch_preview')" :subtitle="__('librarian.copies.marking.batch_preview_hint')"><a class="admin-btn admin-btn-secondary" href="{{ route('librarian.copies.index', ['barcode_status' => 'without']) }}">{{ __('common.actions.back') }}</a></x-admin.page-header>
<div class="mb-6 grid gap-4 sm:grid-cols-3"><div class="admin-card"><p class="admin-label">{{ __('librarian.copies.marking.selected_label') }}</p><p class="mt-2 text-3xl font-bold text-primary">{{ $copies->count() }}</p></div><div class="admin-card"><p class="admin-label">{{ __('librarian.copies.marking.ready') }}</p><p class="mt-2 text-3xl font-bold text-emerald-700">{{ $ready->count() }}</p></div><div class="admin-card"><p class="admin-label">{{ __('librarian.copies.marking.skipped') }}</p><p class="mt-2 text-3xl font-bold text-amber-700">{{ $copies->count() - $ready->count() }}</p></div></div>
<section class="admin-card overflow-hidden p-0"><div class="overflow-x-auto"><table class="admin-table min-w-full"><thead><tr><th>{{ __('librarian.copies.fields.inventory_number') }}</th><th>{{ __('librarian.copies.fields.record') }}</th><th>{{ __('data_quality.object.location') }}</th><th>{{ __('librarian.copies.fields.barcode') }}</th><th>{{ __('common.fields.status') }}</th></tr></thead><tbody>@foreach($copies as $copy)@php $isReady = $ready->contains(fn($item) => $item->is($copy)); @endphp<tr><td class="font-mono font-semibold">{{ $copy->inventory_number }}</td><td>{{ $copy->bibliographicRecord?->title ?? '—' }}</td><td>{{ $copy->branch?->name ?? '—' }} · {{ $copy->fund?->name ?? '—' }} · {{ $copy->shelf_location ?: '—' }}</td><td class="font-mono">{{ $copy->barcode ?: '—' }}</td><td>{{ $isReady ? __('librarian.copies.marking.ready') : __('librarian.copies.marking.not_ready') }}</td></tr>@endforeach</tbody></table></div></section>
@if($ready->isNotEmpty())<form class="admin-card mt-6 flex flex-wrap items-center justify-between gap-4" method="POST" action="{{ route('librarian.copies.barcode-batches.prepare') }}">@csrf @foreach($copies as $copy)<input type="hidden" name="copy_ids[]" value="{{ $copy->id }}">@endforeach<label class="flex max-w-3xl items-start gap-3 text-sm text-slate-700"><input class="mt-1" type="checkbox" name="confirmed" value="1" required><span>{{ __('librarian.copies.marking.batch_confirmation', ['count' => $ready->count()]) }}</span></label><button class="admin-btn admin-btn-primary" type="submit">{{ __('librarian.copies.marking.prepare_and_print') }}</button></form>@endif
@endsection
