@extends('layouts.librarian')
@section('title', $message->ticket_number.' — '.$message->subject)
@section('content')
<x-admin.flash />
@if($errors->any())<div class="mb-5 rounded-xl border border-red-200 bg-red-50 p-4 text-red-900"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<x-admin.page-header :eyebrow="$message->ticket_number" :title="$message->subject" :subtitle="$message->messageCategory?->localizedName()"><a class="admin-btn admin-btn-secondary" href="{{ route('librarian.messages.index') }}">← {{ __('common.actions.back') }}</a></x-admin.page-header>

<div class="grid gap-6 xl:grid-cols-[minmax(0,1fr)_390px]">
<main class="space-y-6">
    <section class="admin-card"><div class="flex flex-wrap justify-between gap-3"><div><strong>{{ $message->sender_name_snapshot ?: $message->sender?->name }}</strong><p class="text-sm text-slate-500">{{ $message->sender_email_snapshot }} · {{ $message->reader_ticket_snapshot }}</p></div><div class="flex gap-2"><x-admin.status-badge :status="$message->status" :label="__('messages.statuses.'.$message->status)" /><x-admin.status-badge :status="$message->priority" :label="__('messages.priorities.'.$message->priority)" /></div></div><p class="mt-5 whitespace-pre-line leading-7 text-slate-700">{{ $message->body }}</p></section>
    <section class="admin-card"><h2 class="font-headline text-2xl text-primary">{{ __('messages.history.title') }}</h2><div class="mt-5 space-y-4">@foreach($thread as $entry)<article class="rounded-xl border p-4 {{ $entry->visibility === 'public' ? 'border-slate-200' : ($entry->visibility === 'director_only' ? 'border-purple-200 bg-purple-50' : 'border-amber-200 bg-amber-50') }}"><div class="flex justify-between gap-3 text-xs text-slate-500"><strong>{{ $entry->author?->name ?? __('messages.system.library') }}</strong><span>{{ $entry->visibility }} · {{ $entry->created_at?->format('d.m.Y H:i') }}</span></div>@if($entry->body)<p class="mt-3 whitespace-pre-line text-sm leading-6">{{ $entry->body }}</p>@endif</article>@endforeach</div></section>
    @if($message->messageAttachments->isNotEmpty())<section class="admin-card"><h2 class="font-headline text-2xl">{{ __('messages.fields.attachments') }}</h2><div class="mt-4 flex flex-wrap gap-2">@foreach($message->messageAttachments as $attachment)<a class="admin-btn admin-btn-secondary" href="{{ route('librarian.messages.attachments.show',[$message,$attachment]) }}"><span class="material-symbols-outlined">download</span>{{ $attachment->original_name }}</a>@endforeach</div></section>@endif
</main>

<aside class="space-y-4">
    @if($message->status === 'open')<form method="POST" action="{{ route('librarian.messages.take',$message) }}" class="admin-card">@csrf<button class="admin-btn admin-btn-primary w-full">{{ __('messages.actions.start_review') }}</button></form>@endif
    @canany(['messages.assign','messages.reassign'])<form method="POST" action="{{ route('librarian.messages.assign',$message) }}" class="admin-card">@csrf @method('PATCH')<label class="admin-label">{{ __('messages.fields.assigned_to') }}</label><select class="admin-input" name="assigned_to"><option value="">{{ __('messages.messages.unassigned') }}</option>@foreach($staff as $person)<option value="{{ $person->id }}" @selected($message->assigned_to === $person->id)>{{ $person->name }} ({{ $person->active_message_load }})</option>@endforeach</select><textarea class="admin-input mt-3" name="reason" required minlength="5" placeholder="{{ __('common.fields.reason') }}"></textarea><button class="admin-btn admin-btn-secondary mt-3 w-full">{{ __('messages.actions.assign') }}</button></form>@endcanany
    @can('messages.prepare_response')@if(!in_array($message->status, ['resolved','rejected','closed'], true))<form method="POST" enctype="multipart/form-data" action="{{ route('librarian.messages.reply',$message) }}" class="admin-card">@csrf<label class="admin-label">{{ __('messages.actions.reply') }}</label><textarea class="admin-input min-h-28" name="body" required></textarea><input class="admin-input mt-3" type="file" name="attachments[]" multiple accept=".jpg,.jpeg,.png,.webp,.pdf,.docx"><button class="admin-btn admin-btn-secondary mt-3 w-full">{{ __('messages.actions.reply') }}</button></form>@endif
    @if($message->status === 'in_review')<form method="POST" action="{{ route('librarian.messages.prepare',$message) }}" class="admin-card">@csrf<label class="admin-label">{{ __('messages.actions.prepare_response') }}</label><textarea class="admin-input min-h-32" name="body" required minlength="5"></textarea><button class="admin-btn admin-btn-primary mt-3 w-full">{{ __('messages.actions.prepare_response') }}</button></form>@endif @endcan
    @can('messages.request_clarification')@if($message->status === 'in_review')<form method="POST" action="{{ route('librarian.messages.clarification',$message) }}" class="admin-card">@csrf<label class="admin-label">{{ __('messages.actions.request_clarification') }}</label><textarea class="admin-input" name="body" required minlength="2"></textarea><button class="admin-btn admin-btn-secondary mt-3 w-full">{{ __('messages.actions.request_clarification') }}</button></form>@endif @endcan
    @can('messages.add_internal_note')<form method="POST" action="{{ route('librarian.messages.notes',$message) }}" class="admin-card">@csrf<label class="admin-label">{{ __('messages.actions.internal_note') }}</label><textarea class="admin-input" name="body" required></textarea><select class="admin-input mt-2" name="visibility"><option value="internal">internal</option><option value="director_only">director_only</option></select><button class="admin-btn admin-btn-secondary mt-3">{{ __('common.actions.add') }}</button></form>@endcan
    @if($message->status === 'response_prepared')@can('messages.approve_response')<form method="POST" action="{{ route('librarian.messages.approve',$message) }}" class="admin-card">@csrf<button class="admin-btn admin-btn-primary w-full">{{ __('messages.actions.approve_response') }}</button></form><form method="POST" action="{{ route('librarian.messages.return-response',$message) }}" class="admin-card">@csrf<textarea class="admin-input" name="reason" required minlength="5"></textarea><button class="admin-btn admin-btn-secondary mt-3 w-full">{{ __('messages.actions.return_response') }}</button></form>@endcan@endif
    @can('messages.change_priority')<form method="POST" action="{{ route('librarian.messages.priority',$message) }}" class="admin-card">@csrf @method('PATCH')<label class="admin-label">{{ __('messages.fields.priority') }}</label><select class="admin-input" name="priority">@foreach(\App\Models\ContactMessage::PRIORITIES as $priority)<option value="{{ $priority }}" @selected($message->priority === $priority)>{{ __('messages.priorities.'.$priority) }}</option>@endforeach</select><textarea class="admin-input mt-3" name="reason" required minlength="5" placeholder="{{ __('common.fields.reason') }}"></textarea><button class="admin-btn admin-btn-secondary mt-3 w-full">{{ __('common.actions.save_changes') }}</button></form>@endcan
    @can('messages.reject')@if(in_array($message->status, ['open','in_review'], true))<form method="POST" action="{{ route('librarian.messages.reject',$message) }}" class="admin-card">@csrf<textarea class="admin-input" name="reason" required minlength="5" placeholder="{{ __('common.fields.reason') }}"></textarea><button class="admin-btn admin-btn-danger mt-3 w-full">{{ __('messages.actions.reject') }}</button></form>@endif @endcan
    @can('messages.close')@if($message->status === 'resolved')<form method="POST" action="{{ route('librarian.messages.close',$message) }}" class="admin-card">@csrf<button class="admin-btn admin-btn-secondary w-full">{{ __('messages.actions.close') }}</button></form>@endif @endcan
    @can('messages.reopen')@if(in_array($message->status, ['resolved','rejected'], true))<form method="POST" action="{{ route('librarian.messages.reopen',$message) }}" class="admin-card">@csrf<textarea class="admin-input" name="reason" required minlength="5" placeholder="{{ __('common.fields.reason') }}"></textarea><button class="admin-btn admin-btn-secondary mt-3 w-full">{{ __('messages.actions.reopen') }}</button></form>@endif @endcan
</aside>
</div>
@endsection
