@extends('layouts.admin')
@section('title', $integration->name.' — '.__('integration_hub.title'))
@section('content')
<x-admin.page-header :title="$integration->name" :subtitle="__('integration_hub.types.'.$integration->type)"><a class="admin-btn admin-btn-secondary" href="{{ route('admin.integrations.index') }}">{{ __('common.actions.back') }}</a></x-admin.page-header>
@if(session('success'))<div class="mb-5 rounded-xl bg-emerald-50 p-4 text-emerald-900">{{ session('success') }}</div>@endif
@if(session('integration_hub_status'))<div class="mb-5 rounded-xl bg-surface-low p-4">{{ __('integration_hub.health') }}: {{ __('integration_hub.statuses.'.session('integration_hub_status')) }}</div>@endif
@php
    $visibleTabs = ['overview', 'configuration', 'capabilities', 'health'];
    if(auth()->user()->can('integrations.view_logs')) $visibleTabs[] = 'sync';
    if(auth()->user()->can('integrations.manage_mapping')) $visibleTabs[] = 'mapping';
    if(auth()->user()->can('integrations.view_conflicts')) $visibleTabs[] = 'conflicts';
    if(auth()->user()->can('integrations.view_logs')) $visibleTabs = [...$visibleTabs, 'inbox', 'outbox', 'errors', 'audit'];
@endphp
<div class="mb-6 flex flex-wrap gap-2">@foreach($visibleTabs as $tab)<a class="rounded-full border px-3 py-2 text-xs font-bold" href="#{{ $tab }}">{{ __('integration_hub.'.$tab) }}</a>@endforeach</div>
<section id="overview" class="admin-card mb-6"><div class="flex justify-between gap-4"><div><h2 class="font-headline text-3xl">{{ __('integration_hub.overview') }}</h2><p class="mt-2 text-sm text-slate-500">{{ $integration->direction }} · {{ $integration->transport }} · {{ $integration->authentication_type }}</p></div><x-admin.status-badge :status="$integration->health_status" :label="__('integration_hub.statuses.'.$integration->health_status)" /></div><dl class="mt-5 grid grid-cols-2 gap-3 lg:grid-cols-4"><div><dt class="text-xs text-slate-500">{{ __('integration_hub.last_success') }}</dt><dd>{{ $integration->last_success_at ?: '—' }}</dd></div><div><dt class="text-xs text-slate-500">{{ __('integration_hub.last_failure') }}</dt><dd>{{ $integration->last_failure_at ?: '—' }}</dd></div><div><dt class="text-xs text-slate-500">{{ __('integration_hub.latency') }}</dt><dd>{{ $integration->last_latency_ms ?? '—' }} ms</dd></div><div><dt class="text-xs text-slate-500">{{ __('integration_hub.responsible') }}</dt><dd>{{ $integration->responsible?->name ?: '—' }}</dd></div></dl></section>
<section id="configuration" class="admin-card mb-6"><h2 class="font-headline text-2xl">{{ __('integration_hub.configuration') }}</h2><p class="mt-3 rounded-lg bg-amber-50 p-4 text-sm">{{ __('integration_hub.secrets_hidden') }}</p><p class="mt-3 text-sm">Environment: {{ $integration->environment }} · config v{{ $integration->config_version }}</p><div class="mt-4 flex gap-3">@can('integrations.manage')<form method="POST" action="{{ route('admin.integrations.toggle',$integration) }}">@csrf<input type="hidden" name="enabled" value="{{ $integration->enabled ? 0 : 1 }}"><input type="hidden" name="confirmation" value="CONFIRM"><button class="admin-btn admin-btn-secondary">{{ $integration->enabled ? __('integration_hub.pause') : __('integration_hub.resume') }}</button></form>@endcan @can('integrations.health')<form method="POST" action="{{ route('admin.integrations.health',$integration) }}">@csrf<button class="admin-btn admin-btn-primary">{{ __('integration_hub.check') }}</button></form>@endcan</div></section>
<section id="capabilities" class="admin-card mb-6"><h2 class="font-headline text-2xl">{{ __('integration_hub.capabilities') }}</h2><div class="mt-4 flex flex-wrap gap-2">@foreach($integration->capabilities ?? [] as $capability)<span class="rounded-full bg-surface-low px-3 py-1 text-xs">{{ $capability }}</span>@endforeach</div></section>
@can('integrations.view_logs')
<section id="sync" class="admin-card mb-6"><div class="flex flex-wrap justify-between gap-3"><h2 class="font-headline text-2xl">{{ __('integration_hub.sync') }}</h2><div class="flex flex-wrap gap-2">@can('integrations.sync')<form method="POST" action="{{ route('admin.integrations.dry-run',$integration) }}">@csrf<button class="admin-btn admin-btn-secondary">{{ __('integration_hub.dry_run') }}</button></form><form method="POST" action="{{ route('admin.integrations.sync', $integration) }}">@csrf<input type="hidden" name="confirmation" value="CONFIRM"><button class="admin-btn admin-btn-secondary">{{ __('integration_hub.start_sync') }}</button></form>@endcan @if($integration->direction === 'bidirectional')@can('integrations.reconcile')<form method="POST" action="{{ route('admin.integrations.reconcile', $integration) }}">@csrf<button class="admin-btn admin-btn-secondary">{{ __('integration_hub.reconcile') }}</button></form>@endcan @endif</div></div><div class="mt-4 overflow-x-auto"><table class="admin-table"><thead><tr><th>Type</th><th>Status</th><th>Received</th><th>Created</th><th>Updated</th><th>Conflicts</th></tr></thead><tbody>@forelse($syncRuns as $run)<tr><td>{{ $run->type }}</td><td>{{ __('integration_hub.statuses.'.$run->status) }}</td><td>{{ $run->received }}</td><td>{{ $run->created }}</td><td>{{ $run->updated }}</td><td>{{ $run->conflicts }}</td></tr>@empty<tr><td colspan="6">—</td></tr>@endforelse</tbody></table></div></section>
@endcan
@can('integrations.manage_mapping')
<section id="mapping" class="admin-card mb-6"><h2 class="font-headline text-2xl">{{ __('integration_hub.mapping') }}</h2>@can('integrations.manage_mapping')<form method="POST" action="{{ route('admin.integrations.mappings.store',$integration) }}" class="mt-4 grid gap-3 md:grid-cols-3">@csrf<input class="admin-input" name="external_field" placeholder="personId" required><select class="admin-input" name="local_field">@foreach(['university_id','email','name','phone','faculty','department','academic_group','status','course','educational_programme'] as $field)<option>{{ $field }}</option>@endforeach</select><button class="admin-btn admin-btn-primary">{{ __('integration_hub.add_mapping') }}</button></form>@endcan<div class="mt-4 overflow-x-auto"><table class="admin-table"><thead><tr><th>Version</th><th>External</th><th>Local</th><th>Transform</th></tr></thead><tbody>@forelse($mappings as $mapping)<tr><td>{{ $mapping->version }}</td><td>{{ $mapping->external_field }}</td><td>{{ $mapping->local_field }}</td><td>{{ $mapping->transform }}</td></tr>@empty<tr><td colspan="4">—</td></tr>@endforelse</tbody></table></div></section>
@endcan
@can('integrations.view_conflicts')
<section id="conflicts" class="admin-card mb-6"><h2 class="font-headline text-2xl">{{ __('integration_hub.conflicts') }}</h2><div class="mt-4 overflow-x-auto"><table class="admin-table"><thead><tr><th>Entity</th><th>Field</th><th>Status</th><th>{{ __('common.fields.actions') }}</th></tr></thead><tbody>@forelse($conflicts as $conflict)<tr><td>{{ $conflict->entity_type }}</td><td>{{ $conflict->field }}</td><td>{{ __('integration_hub.statuses.'.$conflict->status) }}</td><td>
@if($conflict->status === 'open')
    @can('integrations.resolve_conflicts')
        <form method="POST" action="{{ route('admin.integrations.conflicts.resolve', [$integration, $conflict]) }}" class="flex gap-2">@csrf<select name="resolution" class="admin-input"><option value="accept_local">accept local</option><option value="accept_external">accept external</option><option value="manual_fix">manual fix</option><option value="ignore">ignore</option></select><input name="reason" class="admin-input" minlength="5" required><button class="admin-btn admin-btn-secondary">{{ __('integration_hub.resolve') }}</button></form>
    @endcan
@endif
</td></tr>@empty<tr><td colspan="4">—</td></tr>@endforelse</tbody></table></div></section>
@endcan
@can('integrations.view_logs')
<section id="inbox" class="admin-card mb-6"><h2 class="font-headline text-2xl">{{ __('integration_hub.inbox') }}</h2><div class="mt-4 overflow-x-auto"><table class="admin-table"><thead><tr><th>External ID</th><th>Event</th><th>Status</th><th>Hash</th></tr></thead><tbody>@forelse($inbox as $message)<tr><td>{{ $message->external_message_id }}</td><td>{{ $message->event_type }}</td><td>{{ __('integration_hub.statuses.'.$message->status) }}</td><td class="font-mono text-xs">{{ $message->payload_hash }}</td></tr>@empty<tr><td colspan="4">—</td></tr>@endforelse</tbody></table></div></section>
<section id="outbox" class="admin-card mb-6"><h2 class="font-headline text-2xl">{{ __('integration_hub.outbox') }}</h2><div class="mt-4 overflow-x-auto"><table class="admin-table"><thead><tr><th>Event</th><th>Aggregate</th><th>Status</th><th>Attempts</th><th>{{ __('common.fields.actions') }}</th></tr></thead><tbody>@forelse($outbox as $message)<tr><td>{{ $message->event_type }}</td><td>{{ $message->aggregate_type }}:{{ $message->aggregate_id }}</td><td>{{ __('integration_hub.statuses.'.$message->status) }}</td><td>{{ $message->attempts }}</td><td>
@if(in_array($message->status, ['failed', 'dead_letter'], true))
    @can('integrations.retry')
        <form method="POST" action="{{ route('admin.integrations.outbox.retry', [$integration, $message]) }}">@csrf<button class="admin-btn admin-btn-secondary">{{ __('integration_hub.retry') }}</button></form>
    @endcan
@endif
</td></tr>@empty<tr><td colspan="5">—</td></tr>@endforelse</tbody></table></div></section>
<section id="errors" class="admin-card mb-6"><h2 class="font-headline text-2xl">{{ __('integration_hub.errors') }}</h2><p class="mt-3 text-sm text-slate-500">Stable error codes only; payloads and secrets are never rendered.</p></section>
<section id="audit" class="admin-card"><h2 class="font-headline text-2xl">{{ __('integration_hub.audit') }}</h2><p class="mt-3 text-sm text-slate-500">Integration actions are stored in the protected system audit log.</p></section>
@endcan
@endsection
