@php $editing = $publication->exists; @endphp
<div class="mb-6 flex flex-wrap items-start justify-between gap-4">
  <div><p class="text-xs font-bold uppercase tracking-[.18em] text-teal-700">{{ __('news.editor.eyebrow') }}</p><h1 class="font-headline text-4xl text-primary">{{ $editing?__('news.edit'):__('news.create') }}</h1><p class="mt-2 max-w-3xl text-slate-600">{{ __('news.editor.help') }}</p></div>
  <a href="{{ $backUrl }}" class="admin-btn admin-btn-secondary"><span class="material-symbols-outlined">arrow_back</span>{{ __('common.actions.back') }}</a>
</div>
@if($errors->any())<div role="alert" class="mb-6 rounded-xl border border-red-200 bg-red-50 p-4 text-red-800"><strong>{{ __('news.validation.fix_errors') }}</strong><ul class="mt-2 list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form id="news-editor" method="POST" action="{{ $formAction }}" enctype="multipart/form-data" class="grid gap-6 xl:grid-cols-[minmax(0,1fr)_360px]" data-autosave-key="news-editor-{{ $publication->getKey()??'new' }}" data-autosave-url="{{ $autosaveUrl ?? '' }}">
 @csrf @if($editing)@method('PATCH')@endif
 <div class="space-y-6">
  <section class="admin-card"><h2 class="mb-4 text-xl font-bold text-primary">{{ __('news.editor.translations') }}</h2>
   <div class="mb-4 flex gap-2" role="tablist" aria-label="{{ __('news.editor.translations') }}">@foreach(['kk','ru','en'] as $locale)<button type="button" class="rounded-lg border px-4 py-2 font-bold data-[active=true]:bg-primary data-[active=true]:text-white" data-language-tab="{{ $locale }}" data-active="{{ $locale==='kk'?'true':'false' }}">{{ strtoupper($locale) }}{{ $locale==='kk'?' *':'' }}</button>@endforeach</div>
   @foreach(['kk','ru','en'] as $locale)<div class="space-y-4" data-language-panel="{{ $locale }}" @if($locale!=='kk') hidden @endif>
    <div><label class="admin-label" for="title-{{ $locale }}">{{ __('news.fields.title') }} ({{ strtoupper($locale) }})</label><input id="title-{{ $locale }}" class="admin-input" name="title_{{ $locale }}" maxlength="255" value="{{ old('title_'.$locale,$publication->{'title_'.$locale}) }}" @required($locale==='kk')></div>
    <div><label class="admin-label" for="excerpt-{{ $locale }}">{{ __('news.fields.excerpt') }}</label><textarea id="excerpt-{{ $locale }}" class="admin-input min-h-24" name="excerpt_{{ $locale }}" maxlength="1500">{{ old('excerpt_'.$locale,$publication->{'excerpt_'.$locale}) }}</textarea></div>
    <div><label class="admin-label" for="content-{{ $locale }}">{{ __('news.fields.body') }}</label><textarea id="content-{{ $locale }}" class="admin-input min-h-72" name="content_{{ $locale }}" maxlength="150000">{{ old('content_'.$locale,$publication->{'content_'.$locale}) }}</textarea><p class="mt-1 text-xs text-slate-500">{{ __('news.editor.rich_text_hint') }}</p></div>
    <div class="grid gap-4 sm:grid-cols-2"><div><label class="admin-label">Slug</label><input class="admin-input" name="slug_{{ $locale }}" value="{{ old('slug_'.$locale,$publication->{'slug_'.$locale}) }}"></div><div><label class="admin-label">{{ __('news.fields.image_alt') }}</label><input class="admin-input" name="image_alt_{{ $locale }}" value="{{ old('image_alt_'.$locale,$publication->{'image_alt_'.$locale}) }}"></div></div>
   </div>@endforeach
  </section>
  <section class="admin-card"><h2 class="mb-4 text-xl font-bold text-primary">{{ __('news.editor.event_details') }}</h2><div class="grid gap-4 sm:grid-cols-2">
   <div><label class="admin-label">{{ __('news.fields.starts_at') }}</label><input class="admin-input" type="datetime-local" name="starts_at" value="{{ old('starts_at',$publication->starts_at?->format('Y-m-d\TH:i')) }}"></div><div><label class="admin-label">{{ __('news.fields.ends_at') }}</label><input class="admin-input" type="datetime-local" name="ends_at" value="{{ old('ends_at',$publication->ends_at?->format('Y-m-d\TH:i')) }}"></div>
   <div><label class="admin-label">{{ __('news.fields.venue') }}</label><input class="admin-input" name="venue" value="{{ old('venue',$publication->venue) }}"></div><div><label class="admin-label">{{ __('news.fields.online_url') }}</label><input class="admin-input" type="url" name="online_url" value="{{ old('online_url',$publication->online_url) }}"></div>
   <div><label class="admin-label">{{ __('news.fields.organizer') }}</label><input class="admin-input" name="organizer" value="{{ old('organizer',$publication->organizer) }}"></div><div><label class="admin-label">{{ __('news.fields.contact_name') }}</label><input class="admin-input" name="contact_name" value="{{ old('contact_name',$publication->contact_name) }}"></div>
   <div><label class="admin-label">{{ __('news.fields.contact_email') }}</label><input class="admin-input" type="email" name="contact_email" value="{{ old('contact_email',$publication->contact_email) }}"></div><div><label class="admin-label">{{ __('news.fields.contact_phone') }}</label><input class="admin-input" name="contact_phone" value="{{ old('contact_phone',$publication->contact_phone) }}"></div>
   <div><label class="admin-label">{{ __('news.fields.registration_url') }}</label><input class="admin-input" type="url" name="registration_url" value="{{ old('registration_url',$publication->registration_url) }}"></div><div><label class="admin-label">{{ __('news.fields.capacity') }}</label><input class="admin-input" type="number" min="1" name="capacity" value="{{ old('capacity',$publication->capacity) }}"></div>
   <div><label class="admin-label">{{ __('news.fields.expires_at') }}</label><input class="admin-input" type="datetime-local" name="expires_at" value="{{ old('expires_at',$publication->expires_at?->format('Y-m-d\TH:i')) }}"></div><div><label class="admin-label">{{ __('news.fields.homepage_until') }}</label><input class="admin-input" type="datetime-local" name="homepage_until" value="{{ old('homepage_until',$publication->homepage_until?->format('Y-m-d\TH:i')) }}"></div>
   <div class="sm:col-span-2"><label class="admin-label">{{ __('news.fields.source') }}</label><input class="admin-input" name="source" maxlength="255" value="{{ old('source',$publication->source) }}"></div>
  </div></section>
 </div>
 <aside class="space-y-6">
  <section class="admin-card space-y-4"><div class="flex items-center justify-between"><h2 class="text-xl font-bold text-primary">{{ __('news.editor.settings') }}</h2>@if($editing)<x-admin.status-badge :status="in_array($publication->status,['published','approved'],true)?'success':($publication->status==='changes_requested'?'danger':'warning')" :label="__('news.statuses.'.$publication->status)"/>@endif</div>
   <div><label class="admin-label">{{ __('news.fields.type') }}</label><select class="admin-input" name="type" required>@foreach(\App\Models\News::TYPES as $type)<option value="{{ $type }}" @selected(old('type',$publication->type)===$type)>{{ __('news.types.'.$type) }}</option>@endforeach</select></div>
   <div><label class="admin-label">{{ __('news.fields.category') }}</label><select class="admin-input" name="category_id"><option value="">—</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((string)old('category_id',$publication->category_id)===(string)$category->id)>{{ $category->name() }}</option>@endforeach</select></div>
   <div><label class="admin-label">{{ __('news.fields.audience') }}</label><input class="admin-input" name="audience" value="{{ old('audience',$publication->audience) }}"></div>
    <div><label class="admin-label">{{ __('news.fields.annual_plan') }}</label><select class="admin-input" name="annual_plan_item_id"><option value="">—</option>@foreach($planItems as $planItem)<option value="{{ $planItem->id }}" @selected((string)old('annual_plan_item_id',$publication->annual_plan_item_id)===(string)$planItem->id)>{{ $planItem->planned_date->format('d.m.Y') }} · {{ $planItem->title_kk }}</option>@endforeach</select></div>
   <div><label class="admin-label">{{ __('news.fields.repository_work') }}</label><select class="admin-input" name="repository_item_id"><option value="">—</option>@foreach(($repositoryWorks ?? collect()) as $work)<option value="{{ $work->id }}" @selected((string)old('repository_item_id',$publication->repository_item_id)===(string)$work->id)>{{ $work->title }}{{ $work->year ? ' · '.$work->year : '' }}</option>@endforeach</select><p class="mt-1 text-xs text-slate-500">{{ __('news.editor.repository_help') }}</p></div>
   <div><label class="admin-label">{{ __('news.fields.cover_image') }}</label>@if($publication->cover_image)<img class="mb-2 aspect-video w-full rounded-lg object-cover" src="{{ asset('storage/'.$publication->cover_image) }}" alt="{{ $publication->localized('image_alt') }}">@endif<input class="admin-input" type="file" name="cover_image" accept="image/jpeg,image/png,image/webp"><p class="mt-1 text-xs text-slate-500">{{ __('news.cover.hint') }}</p></div>
   <div><label class="admin-label">{{ __('news.fields.importance') }}</label><select class="admin-input" name="importance">@foreach(['normal','important','critical'] as $value)<option value="{{ $value }}" @selected(old('importance',$publication->importance??'normal')===$value)>{{ __('news.importance.'.$value) }}</option>@endforeach</select></div>
   <div><label class="admin-label">{{ __('news.fields.visibility') }}</label><select class="admin-input" name="visibility">@foreach(['public','members','staff'] as $value)<option value="{{ $value }}" @selected(old('visibility',$publication->visibility??'public')===$value)>{{ __('news.visibility.'.$value) }}</option>@endforeach</select></div>
   <div><label class="admin-label">{{ __('news.fields.homepage_priority') }}</label><input class="admin-input" type="number" min="0" max="1000" name="homepage_priority" value="{{ old('homepage_priority',$publication->homepage_priority??0) }}"></div>
   @can('news.manage_homepage')<label class="flex gap-2"><input type="checkbox" name="show_on_homepage" value="1" @checked(old('show_on_homepage',$publication->show_on_homepage))><span>{{ __('news.fields.show_on_homepage') }}</span></label><label class="flex gap-2"><input type="checkbox" name="is_featured" value="1" @checked(old('is_featured',$publication->is_featured))><span>{{ __('news.fields.is_featured') }}</span></label>@endcan
   <button class="admin-btn admin-btn-primary w-full" type="submit"><span class="material-symbols-outlined">save</span>{{ __('common.actions.save') }}</button>@if($editing && request()->routeIs('librarian.*'))<a class="admin-btn admin-btn-secondary w-full" target="_blank" rel="noopener" href="{{ \Illuminate\Support\Facades\URL::temporarySignedRoute('librarian.news.preview', now()->addMinutes(20), $publication) }}">{{ __('news.preview') }}</a>@endif<p id="autosave-state" class="text-center text-xs text-slate-500" aria-live="polite">{{ __('news.editor.autosave_local') }}</p>
  </section>
 </aside>
</form>
@if($editing)
<section class="admin-card mt-6"><h2 class="text-xl font-bold text-primary">{{ __('news.editor.workflow') }}</h2><div class="mt-4 flex flex-wrap gap-3">
 @php $actions = match($publication->status) {'draft'=>['pending_review'],'pending_review'=>['approved','changes_requested'],'changes_requested'=>['draft'],'approved'=>['published','scheduled'],'scheduled'=>['cancelled'],'published'=>['archived','cancelled'],'archived'=>['published'],default=>[]}; @endphp
 @foreach($actions as $to)@php $permission = match($to) {'pending_review'=>'news.submit_for_review','approved'=>'news.approve','changes_requested'=>'news.request_changes','scheduled'=>'news.schedule','published'=>'news.publish','archived'=>'news.archive','cancelled'=>'news.cancel',default=>'news.edit_own'}; @endphp @can($permission)<form method="POST" action="{{ $transitionRoute }}" class="flex flex-wrap items-end gap-2 rounded-xl border p-3">@csrf<input type="hidden" name="status" value="{{ $to }}">@if($to==='scheduled')<label class="text-xs">{{ __('news.fields.publish_at') }}<input class="admin-input mt-1" type="datetime-local" name="scheduled_publish_at" required></label>@endif @if(in_array($to,['changes_requested','cancelled','published'],true)&&($to!=='published'||$publication->status==='archived'))<label class="text-xs">{{ __('news.fields.comment') }}<textarea class="admin-input mt-1" name="{{ $to==='changes_requested'?'comment':'reason' }}" required></textarea></label>@endif<button class="admin-btn {{ in_array($to,['cancelled','changes_requested'],true)?'admin-btn-secondary':'admin-btn-primary' }}" type="submit">{{ __('news.actions.'.$to) }}</button></form>@endcan @endforeach
 </div><div class="mt-6 border-t pt-4"><h3 class="font-bold">{{ __('news.editor.review_history') }}</h3><ol class="mt-3 space-y-2">@forelse($publication->reviews()->with('actor')->latest()->get() as $review)<li class="rounded-lg bg-slate-50 p-3 text-sm"><strong>{{ __('news.statuses.'.$review->action) }}</strong> · {{ $review->actor?->name??__('common.system') }} · {{ $review->created_at->format('d.m.Y H:i') }} @if($review->comment)<p>{{ $review->comment }}</p>@endif</li>@empty<li class="text-sm text-slate-500">{{ __('news.editor.no_reviews') }}</li>@endforelse</ol></div></section>
@endif
<script>document.querySelectorAll('[data-language-tab]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-language-tab]').forEach(x=>x.dataset.active=String(x===button));document.querySelectorAll('[data-language-panel]').forEach(x=>x.hidden=x.dataset.languagePanel!==button.dataset.languageTab)}));const editor=document.getElementById('news-editor');const key=editor.dataset.autosaveKey;const fields=[...editor.querySelectorAll('input:not([type=file]):not([name=_token]),textarea,select')];const saved=localStorage.getItem(key);if(saved&&!@json($editing)){try{const values=JSON.parse(saved);fields.forEach(f=>{if(values[f.name]!==undefined){if(f.type==='checkbox')f.checked=values[f.name];else if(!f.value)f.value=values[f.name]}})}catch{}}let localTimer,serverTimer,dirty=false;const saveLocal=()=>{const values={};fields.forEach(x=>values[x.name]=x.type==='checkbox'?x.checked:x.value);localStorage.setItem(key,JSON.stringify(values));document.getElementById('autosave-state').textContent=@json(__('news.editor.autosaved_local'))};const saveServer=async()=>{if(!dirty||!editor.dataset.autosaveUrl)return;const data=new FormData(editor);data.delete('_method');data.delete('cover_image');try{const response=await fetch(editor.dataset.autosaveUrl,{method:'POST',body:data,headers:{Accept:'application/json'},credentials:'same-origin'});if(!response.ok)throw new Error(String(response.status));dirty=false;document.getElementById('autosave-state').textContent=@json(__('news.editor.autosaved_server'))}catch{document.getElementById('autosave-state').textContent=@json(__('news.editor.autosave_failed'))}};fields.forEach(f=>f.addEventListener('input',()=>{dirty=true;clearTimeout(localTimer);localTimer=setTimeout(saveLocal,1200);clearTimeout(serverTimer);serverTimer=setTimeout(saveServer,30000)}));editor.addEventListener('submit',()=>{clearTimeout(serverTimer);localStorage.removeItem(key)});</script>
