@extends('layouts.librarian')

@section('title', __('operations.ksu.title'))

@section('content')
<div class="space-y-6">
    <header class="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p class="admin-kicker">{{ __('operations.ksu.kicker') }}</p><h1 class="font-headline text-4xl text-primary">{{ __('operations.ksu.title') }}</h1><p class="mt-2 max-w-3xl text-slate-600">{{ __('operations.ksu.description') }}</p></div><div class="flex flex-wrap gap-3">@canany(['acquisitions.view','acquisitions.manage'])<a class="admin-btn admin-btn-secondary" href="{{ route('librarian.acquisitions.index') }}">{{ __('operations.acquisitions.title') }}</a>@endcanany @can('ksu.manage')<a class="admin-btn admin-btn-primary" href="{{ route('librarian.ksu.conflicts') }}">{{ __('operations.ksu.open_conflicts', ['count' => number_format($openConflicts, 0, ',', ' ')]) }}</a>@endcan</div></header>

    <section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">@foreach($books as $book)<article class="admin-card"><p class="text-xs font-bold uppercase tracking-widest text-secondary">{{ $book->code }}</p><h2 class="mt-2 font-headline text-xl text-primary">{{ $book->name }}</h2><dl class="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt class="text-slate-500">{{ __('operations.ksu.entries') }}</dt><dd class="text-xl font-bold">{{ number_format($book->entries_count, 0, ',', ' ') }}</dd></div><div><dt class="text-slate-500">{{ __('operations.ksu.conflicts') }}</dt><dd class="text-xl font-bold">{{ number_format($book->conflicts_count, 0, ',', ' ') }}</dd></div></dl></article>@endforeach</section>

    <section class="admin-card"><form method="GET" action="{{ route('librarian.ksu.index') }}" class="grid gap-3 sm:grid-cols-2 lg:grid-cols-[minmax(0,1fr)_8rem_14rem_12rem_auto]"><label><span class="admin-label">{{ __('operations.common.search') }}</span><input class="admin-input" type="search" name="q" value="{{ request('q') }}"></label><label><span class="admin-label">{{ __('operations.ksu.year') }}</span><input class="admin-input" type="number" min="1900" max="9999" name="year" value="{{ request('year') }}"></label><label><span class="admin-label">{{ __('operations.ksu.book') }}</span><select class="admin-input" name="book"><option value="">{{ __('operations.common.all') }}</option>@foreach($books as $book)<option value="{{ $book->id }}" @selected((string) request('book') === (string) $book->id)>{{ $book->code }}</option>@endforeach</select></label><label><span class="admin-label">{{ __('operations.common.status') }}</span><select class="admin-input" name="status"><option value="">{{ __('operations.common.all') }}</option>@foreach(['legacy','draft','posted'] as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ $status }}</option>@endforeach</select></label><button class="admin-btn admin-btn-secondary self-end" type="submit">{{ __('operations.common.filter') }}</button></form></section>

    <section class="admin-card overflow-hidden"><h2 class="font-headline text-2xl text-primary">{{ __('operations.ksu.entries') }}</h2><div class="mt-4 overflow-x-auto"><table class="admin-table min-w-[900px]"><thead><tr><th>{{ __('operations.ksu.book') }}</th><th>{{ __('operations.ksu.entry_number') }}</th><th>{{ __('operations.common.date') }}</th><th>{{ __('operations.ksu.operation') }}</th><th>{{ __('operations.ksu.supplier_or_act') }}</th><th>{{ __('operations.acquisitions.titles') }}</th><th>{{ __('operations.acquisitions.copies') }}</th><th>{{ __('operations.ksu.cost') }}</th><th></th></tr></thead><tbody>
        @forelse($entries as $entry)<tr><td>{{ $entry->book?->code }}</td><td class="font-bold text-primary">{{ $entry->entry_number }}</td><td>{{ $entry->entry_date?->format('d.m.Y') ?: '—' }}</td><td>{{ __('operations.ksu.operation_types.'.$entry->operation_type) }}</td><td>{{ $entry->act_number ?: ($entry->supplier_name ?: '—') }}</td><td>{{ $entry->title_count }}</td><td>{{ $entry->copy_count }}</td><td>{{ $entry->total_cost === null ? '—' : number_format((float) $entry->total_cost, 2, ',', ' ') }}</td><td><a class="font-semibold text-secondary" href="{{ route('librarian.ksu.show', $entry) }}">{{ __('operations.common.open') }}</a></td></tr>
        @empty<tr><td colspan="9" class="py-8 text-center text-slate-500">{{ __('operations.ksu.empty') }}</td></tr>@endforelse
    </tbody></table></div><div class="mt-5">{{ $entries->links() }}</div></section>

    <details class="admin-card"><summary class="cursor-pointer font-headline text-2xl text-primary">{{ __('operations.ksu.sequences') }}</summary><div class="mt-4 overflow-x-auto"><table class="admin-table min-w-[600px]"><thead><tr><th>{{ __('operations.ksu.book') }}</th><th>{{ __('operations.ksu.year') }}</th><th>{{ __('operations.ksu.last_number') }}</th><th>{{ __('operations.ksu.observed_max') }}</th><th>{{ __('operations.ksu.allocation') }}</th></tr></thead><tbody>@foreach($sequences as $sequence)<tr><td>{{ $sequence->book?->code }}</td><td>{{ $sequence->year }}</td><td>{{ $sequence->last_number }}</td><td>{{ $sequence->max_observed ?? '—' }}</td><td>{{ $sequence->allocation_enabled ? __('operations.ksu.enabled') : __('operations.ksu.disabled') }}</td></tr>@endforeach</tbody></table></div></details>
</div>
@endsection
