@extends('layouts.librarian')

@section('title', $entry->entry_number)

@section('content')
<div class="space-y-6">
    <header><a class="text-sm font-semibold text-secondary hover:underline" href="{{ route('librarian.ksu.index') }}">← {{ __('operations.common.back') }}</a><p class="admin-kicker mt-3">{{ $entry->book?->code }}</p><h1 class="font-headline text-4xl text-primary">{{ $entry->entry_number }}</h1></header>
    <section class="admin-card"><dl class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div><dt class="admin-label">{{ __('operations.common.date') }}</dt><dd>{{ $entry->entry_date?->format('d.m.Y') ?: '—' }}</dd></div><div><dt class="admin-label">{{ __('operations.ksu.operation') }}</dt><dd>{{ __('operations.ksu.operation_types.'.$entry->operation_type) }}</dd></div><div><dt class="admin-label">{{ __('operations.acquisitions.supplier') }}</dt><dd>{{ $entry->supplier_name ?: '—' }}</dd></div><div><dt class="admin-label">{{ __('operations.acquisitions.source') }}</dt><dd>{{ $entry->acquisition_source ?: '—' }}</dd></div><div><dt class="admin-label">{{ __('operations.ksu.supplier_or_act') }}</dt><dd>{{ $entry->act_number ?: '—' }}</dd></div><div><dt class="admin-label">{{ __('operations.acquisitions.titles') }}</dt><dd>{{ $entry->title_count }}</dd></div><div><dt class="admin-label">{{ __('operations.acquisitions.copies') }}</dt><dd>{{ $entry->copy_count }}</dd></div><div><dt class="admin-label">{{ __('operations.ksu.cost') }}</dt><dd>{{ $entry->total_cost === null ? '—' : number_format((float) $entry->total_cost, 2, ',', ' ') }}</dd></div><div><dt class="admin-label">{{ __('operations.acquisitions.batch') }}</dt><dd>@if($entry->acquisitionBatch)<a class="font-semibold text-secondary" href="{{ route('librarian.acquisitions.show', $entry->acquisitionBatch) }}">{{ $entry->acquisitionBatch->batch_number }}</a>@else—@endif</dd></div>@if($entry->operation_reason)<div class="sm:col-span-2 lg:col-span-4"><dt class="admin-label">{{ __('operations.ksu.reason') }}</dt><dd>{{ $entry->operation_reason }}</dd></div>@endif</dl></section>
    <section class="admin-card overflow-hidden"><h2 class="font-headline text-2xl text-primary">{{ __('operations.ksu.items') }}</h2><div class="mt-4 overflow-x-auto"><table class="admin-table min-w-[980px]"><thead><tr><th>{{ __('operations.acquisitions.record') }}</th><th>{{ __('operations.ksu.ksu_number') }}</th><th>{{ __('operations.acquisitions.inventory_number') }}</th><th>{{ __('operations.acquisitions.barcode') }}</th><th>{{ __('operations.acquisitions.unit_price') }}</th><th>{{ __('operations.ksu.registration_date') }}</th><th>{{ __('operations.acquisitions.source') }}</th><th>{{ __('operations.common.status') }}</th></tr></thead><tbody>@foreach($items as $item)<tr><td>{{ $item->bibliographicRecord?->title ?: '—' }}@if($item->bibliographicRecord?->primary_author)<span class="block text-xs text-slate-500">{{ $item->bibliographicRecord->primary_author }}</span>@endif</td><td>{{ $item->copy?->ksu_number ?: $entry->entry_number }}</td><td>{{ $item->inventory_number ?: $item->copy?->inventory_number }}</td><td>{{ $item->copy?->barcode ?: '—' }}</td><td>{{ $item->price === null ? '—' : number_format((float) $item->price, 2, ',', ' ') }}</td><td>{{ ($item->registration_date ?? $item->copy?->registration_date)?->format('d.m.Y') ?: '—' }}</td><td>{{ $item->copy?->acquisition_source ?: ($entry->acquisition_source ?: '—') }}</td><td>{{ $item->copy ? (($item->copy->inventory_status ?: $item->copy->status).' / '.($item->copy->circulation_status ?: '—')) : '—' }}</td></tr>@endforeach</tbody></table></div><div class="mt-5">{{ $items->links() }}</div></section>
</div>
@endsection
